//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldOaModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class caigouEntities : DbContext
    {
        public caigouEntities()
            : base("name=caigouEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_BaiFenbi> T_BaiFenbi { get; set; }
        public DbSet<T_BmName> T_BmName { get; set; }
        public DbSet<T_CarUsers> T_CarUsers { get; set; }
        public DbSet<T_CgUser> T_CgUser { get; set; }
        public DbSet<T_Cgxj> T_Cgxj { get; set; }
        public DbSet<T_Classes> T_Classes { get; set; }
        public DbSet<T_CMZtable> T_CMZtable { get; set; }
        public DbSet<T_Dw> T_Dw { get; set; }
        public DbSet<T_EverMonthhaoyou> T_EverMonthhaoyou { get; set; }
        public DbSet<T_Gonggao> T_Gonggao { get; set; }
        public DbSet<T_Gongwen> T_Gongwen { get; set; }
        public DbSet<T_Huobukaoqin> T_Huobukaoqin { get; set; }
        public DbSet<T_HuoyunErverday> T_HuoyunErverday { get; set; }
        public DbSet<T_HuoyunLCS> T_HuoyunLCS { get; set; }
        public DbSet<T_HuoyunLj> T_HuoyunLj { get; set; }
        public DbSet<T_HuoyunMoth> T_HuoyunMoth { get; set; }
        public DbSet<T_Leibie> T_Leibie { get; set; }
        public DbSet<T_lnlyysjt> T_lnlyysjt { get; set; }
        public DbSet<T_LoginBak> T_LoginBak { get; set; }
        public DbSet<T_MAIN_GUNDONG> T_MAIN_GUNDONG { get; set; }
        public DbSet<T_OutDORshijian> T_OutDORshijian { get; set; }
        public DbSet<T_Over_car> T_Over_car { get; set; }
        public DbSet<T_Person> T_Person { get; set; }
        public DbSet<T_Personmoney> T_Personmoney { get; set; }
        public DbSet<T_QJDtable> T_QJDtable { get; set; }
        public DbSet<T_Qx_bumen> T_Qx_bumen { get; set; }
        public DbSet<T_SqTable> T_SqTable { get; set; }
        public DbSet<T_SysUsers> T_SysUsers { get; set; }
        public DbSet<T_Tiaodian> T_Tiaodian { get; set; }
        public DbSet<T_UseCart> T_UseCart { get; set; }
        public DbSet<T_Users> T_Users { get; set; }
        public DbSet<T_Users_content> T_Users_content { get; set; }
        public DbSet<T_Wuguan> T_Wuguan { get; set; }
        public DbSet<T_Wuguanchuku> T_Wuguanchuku { get; set; }
        public DbSet<T_ZaoBiaoFanWei> T_ZaoBiaoFanWei { get; set; }
        public DbSet<T_Caigou> T_Caigou { get; set; }
    }
}
