//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldOaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Cgxj
    {
        public long id { get; set; }
        public string clname { get; set; }
        public string ggxh { get; set; }
        public string cpcd { get; set; }
        public decimal cpsl { get; set; }
        public string bmname { get; set; }
        public string bz { get; set; }
        public string cpdw { get; set; }
        public System.DateTime Sctime { get; set; }
        public string Cjtime { get; set; }
        public string Delet { get; set; }
        public System.DateTime Overtime { get; set; }
        public string Zt { get; set; }
        public string WOver { get; set; }
        public Nullable<int> Lebie { get; set; }
        public Nullable<int> dlt { get; set; }
    }
}
