//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldOaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CMZtable
    {
        public long id { get; set; }
        public string Bumen { get; set; }
        public string Person { get; set; }
        public string Leibie { get; set; }
        public string Danwei { get; set; }
        public System.DateTime Gotime { get; set; }
        public string Gom { get; set; }
        public System.DateTime Backtime { get; set; }
        public string Backmuent { get; set; }
        public string Fzr { get; set; }
        public int dlt { get; set; }
        public System.DateTime SavTime { get; set; }
        public Nullable<int> See { get; set; }
        public Nullable<int> dlt_all { get; set; }
    }
}
