//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldOaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HuoyunErverday
    {
        public long id { get; set; }
        public System.DateTime Time { get; set; }
        public string CarNumberid { get; set; }
        public long CarPersonid { get; set; }
        public decimal money { get; set; }
        public decimal Gls { get; set; }
        public int dlt { get; set; }
        public Nullable<int> items { get; set; }
    }
}
