//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldOaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HuoyunMoth
    {
        public long id { get; set; }
        public decimal Gqf { get; set; }
        public decimal Fakuan { get; set; }
        public decimal Xcf { get; set; }
        public decimal Bxfy { get; set; }
        public decimal Jcf { get; set; }
        public decimal jwlxh { get; set; }
        public decimal Lj { get; set; }
        public decimal Gz { get; set; }
        public decimal Flf { get; set; }
        public decimal Clf { get; set; }
        public decimal Qt { get; set; }
        public decimal Gy { get; set; }
        public decimal Ltt { get; set; }
        public Nullable<int> dlt { get; set; }
        public System.DateTime Dtime { get; set; }
    }
}
