//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldOaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_lnlyysjt
    {
        public long id { get; set; }
        public string Comname { get; set; }
        public string Photo { get; set; }
        public string Lxperson { get; set; }
        public string Lxqq { get; set; }
        public string Qqquen { get; set; }
        public string JsPhoto { get; set; }
    }
}
