//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldOaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Personmoney
    {
        public long id { get; set; }
        public string Username { get; set; }
        public decimal Company { get; set; }
        public long CgxjId { get; set; }
        public string Jsfs { get; set; }
        public string Bz { get; set; }
        public string Cpcz { get; set; }
        public string Cpcd { get; set; }
        public string Cppp { get; set; }
        public string Xjzt { get; set; }
        public string Sctime { get; set; }
        public string Cjtime { get; set; }
        public string Overtime { get; set; }
        public string clname { get; set; }
        public string ggxh { get; set; }
        public string cpdw { get; set; }
        public decimal cpsl { get; set; }
        public string bmname { get; set; }
        public string Zbzt { get; set; }
        public string ZbPerson { get; set; }
        public Nullable<decimal> Zbje { get; set; }
        public string Zbbz { get; set; }
        public string bzs { get; set; }
        public decimal yunfei { get; set; }
        public string xjbz { get; set; }
        public Nullable<int> Lebie { get; set; }
    }
}
