//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldOaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SqTable
    {
        public long id { get; set; }
        public string clname { get; set; }
        public string ggxh { get; set; }
        public string cpcd { get; set; }
        public string cpsl { get; set; }
        public string bmname { get; set; }
        public string bz { get; set; }
        public string cpdw { get; set; }
        public string SqTime { get; set; }
        public string Dyt { get; set; }
        public string Sqperson { get; set; }
        public string Sqbumen { get; set; }
        public string Deletes { get; set; }
        public string Dsname { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<long> Cgxj_id { get; set; }
        public string Sl { get; set; }
        public string Cgname { get; set; }
        public string Caiwu { get; set; }
        public string Cwname { get; set; }
        public Nullable<int> Lebie { get; set; }
    }
}
