//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldOaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UseCart
    {
        public long id { get; set; }
        public System.DateTime Thetime { get; set; }
        public string CartPerson { get; set; }
        public string Cartccr { get; set; }
        public Nullable<int> cclcs { get; set; }
        public Nullable<int> sclcs { get; set; }
        public Nullable<System.DateTime> Gotime { get; set; }
        public Nullable<System.DateTime> Backtime { get; set; }
        public string Goaddess { get; set; }
        public string Toyes { get; set; }
        public string Tono { get; set; }
        public string xsgss { get; set; }
        public string Toshiyou { get; set; }
        public string Txt { get; set; }
        public string CartNumber { get; set; }
        public string Cartname { get; set; }
        public string bmfzr { get; set; }
        public int dlt { get; set; }
        public System.DateTime savetime { get; set; }
        public string Bumen { get; set; }
        public Nullable<int> Mw_dlt { get; set; }
        public Nullable<int> YXB_sh { get; set; }
    }
}
