//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldOaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Wuguan
    {
        public long id { get; set; }
        public string Personname { get; set; }
        public string Bumen { get; set; }
        public string Wupin { get; set; }
        public int Zhuangtai { get; set; }
        public decimal Shuliang { get; set; }
        public string Guige { get; set; }
        public System.DateTime Sqtime { get; set; }
        public System.DateTime Shtime { get; set; }
        public string Money { get; set; }
        public string SumMoney { get; set; }
        public string Danwei { get; set; }
        public string Beizhu { get; set; }
        public string SHperson { get; set; }
        public Nullable<int> dlt { get; set; }
        public Nullable<int> prt { get; set; }
    }
}
