//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_Account_AuxProperty
    {
        public int id { get; set; }
        public string auxaccitem { get; set; }
        public string auxaccsourcetype { get; set; }
        public int idaccountdto { get; set; }
        public Nullable<int> accountingyear { get; set; }
        public Nullable<int> idAuxAcc { get; set; }
        public byte[] ts { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    }
}
