//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_Account_Ext
    {
        public string accountcode_lev1 { get; set; }
        public string accountname_lev1 { get; set; }
        public string accountcode_lev2 { get; set; }
        public string accountname_lev2 { get; set; }
        public string accountcode_lev3 { get; set; }
        public string accountname_lev3 { get; set; }
        public string accountcode_lev4 { get; set; }
        public string accountname_lev4 { get; set; }
        public string accountcode_lev5 { get; set; }
        public string accountname_lev5 { get; set; }
        public string accountcode_lev6 { get; set; }
        public string accountname_lev6 { get; set; }
        public string accountcode_lev7 { get; set; }
        public string accountname_lev7 { get; set; }
        public string accountcode_lev8 { get; set; }
        public string accountname_lev8 { get; set; }
        public string accountcode_lev9 { get; set; }
        public string accountname_lev9 { get; set; }
        public string accountcode_lev10 { get; set; }
        public string accountname_lev10 { get; set; }
        public string accountcode_lev11 { get; set; }
        public string accountname_lev11 { get; set; }
        public string accountcode_lev12 { get; set; }
        public string accountname_lev12 { get; set; }
        public string accountcode_lev13 { get; set; }
        public string accountname_lev13 { get; set; }
        public string accountcode_lev14 { get; set; }
        public string accountname_lev14 { get; set; }
        public string accountcode_lev15 { get; set; }
        public string accountname_lev15 { get; set; }
        public string depth { get; set; }
        public byte[] ts { get; set; }
        public Nullable<int> accountid_lev1 { get; set; }
        public Nullable<int> accountid_lev10 { get; set; }
        public Nullable<int> accountid_lev11 { get; set; }
        public Nullable<int> accountid_lev12 { get; set; }
        public Nullable<int> accountid_lev13 { get; set; }
        public Nullable<int> accountid_lev14 { get; set; }
        public Nullable<int> accountid_lev15 { get; set; }
        public Nullable<int> accountid_lev2 { get; set; }
        public Nullable<int> accountid_lev3 { get; set; }
        public Nullable<int> accountid_lev4 { get; set; }
        public Nullable<int> accountid_lev5 { get; set; }
        public Nullable<int> accountid_lev6 { get; set; }
        public Nullable<int> accountid_lev7 { get; set; }
        public Nullable<int> accountid_lev8 { get; set; }
        public Nullable<int> accountid_lev9 { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
    }
}
