//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_AccountType
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> trialbalancedirection { get; set; }
        public Nullable<int> firstnumber { get; set; }
        public Nullable<byte> trialbalance { get; set; }
        public Nullable<int> accountClass { get; set; }
        public byte[] ts { get; set; }
        public string classcode { get; set; }
        public int id { get; set; }
        public Nullable<int> defaultdcdirection { get; set; }
        public string industryTypeCode { get; set; }
    }
}
