//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_BarCodeTermAnalysisInfo
    {
        public string code { get; set; }
        public string name { get; set; }
        public string updatedBy { get; set; }
        public byte[] ts { get; set; }
        public Nullable<byte> Information1 { get; set; }
        public Nullable<byte> Information2 { get; set; }
        public Nullable<byte> Information3 { get; set; }
        public Nullable<byte> Information4 { get; set; }
        public Nullable<byte> Information5 { get; set; }
        public Nullable<byte> Information6 { get; set; }
        public Nullable<byte> Information7 { get; set; }
        public Nullable<byte> Information8 { get; set; }
        public Nullable<byte> Information9 { get; set; }
        public Nullable<byte> Information10 { get; set; }
        public Nullable<byte> Information11 { get; set; }
        public Nullable<byte> Information12 { get; set; }
        public Nullable<byte> Information13 { get; set; }
        public Nullable<byte> Information14 { get; set; }
        public Nullable<byte> Information15 { get; set; }
        public Nullable<byte> Information16 { get; set; }
        public Nullable<byte> Information17 { get; set; }
        public Nullable<byte> Information18 { get; set; }
        public Nullable<byte> Information19 { get; set; }
        public Nullable<byte> Information20 { get; set; }
        public Nullable<byte> Information21 { get; set; }
        public Nullable<byte> Information22 { get; set; }
        public Nullable<byte> Information23 { get; set; }
        public Nullable<byte> Information24 { get; set; }
        public Nullable<byte> Information25 { get; set; }
        public Nullable<byte> Information26 { get; set; }
        public Nullable<byte> Information27 { get; set; }
        public Nullable<byte> Information28 { get; set; }
        public Nullable<byte> Information29 { get; set; }
        public Nullable<byte> Information30 { get; set; }
        public Nullable<byte> Information31 { get; set; }
        public Nullable<byte> Information32 { get; set; }
        public Nullable<byte> Information33 { get; set; }
        public Nullable<byte> Information34 { get; set; }
        public Nullable<byte> Information35 { get; set; }
        public Nullable<byte> Information36 { get; set; }
        public Nullable<byte> Information37 { get; set; }
        public Nullable<byte> Information38 { get; set; }
        public Nullable<byte> Information39 { get; set; }
        public Nullable<byte> Information40 { get; set; }
        public Nullable<byte> Information41 { get; set; }
        public Nullable<byte> Information42 { get; set; }
        public Nullable<byte> Information43 { get; set; }
        public Nullable<byte> Information44 { get; set; }
        public Nullable<byte> Information45 { get; set; }
        public Nullable<byte> Information46 { get; set; }
        public Nullable<byte> Information47 { get; set; }
        public Nullable<byte> Information48 { get; set; }
        public Nullable<byte> Information49 { get; set; }
        public Nullable<byte> Information50 { get; set; }
        public Nullable<byte> Information51 { get; set; }
        public Nullable<byte> Information52 { get; set; }
        public Nullable<byte> Information53 { get; set; }
        public Nullable<byte> Information54 { get; set; }
        public Nullable<byte> Information55 { get; set; }
        public Nullable<byte> Information56 { get; set; }
        public Nullable<byte> Information57 { get; set; }
        public Nullable<byte> Information58 { get; set; }
        public Nullable<byte> Information59 { get; set; }
        public Nullable<byte> Information60 { get; set; }
        public Nullable<byte> Information61 { get; set; }
        public Nullable<byte> Information62 { get; set; }
        public Nullable<byte> Information63 { get; set; }
        public Nullable<byte> Information64 { get; set; }
        public Nullable<byte> Information65 { get; set; }
        public Nullable<byte> Information66 { get; set; }
        public Nullable<byte> Information67 { get; set; }
        public Nullable<byte> Information68 { get; set; }
        public Nullable<byte> Information69 { get; set; }
        public Nullable<byte> Information70 { get; set; }
        public Nullable<byte> Information71 { get; set; }
        public Nullable<byte> Information72 { get; set; }
        public Nullable<byte> Information73 { get; set; }
        public Nullable<byte> Information74 { get; set; }
        public Nullable<byte> Information75 { get; set; }
        public Nullable<byte> Information76 { get; set; }
        public Nullable<byte> Information77 { get; set; }
        public Nullable<byte> Information78 { get; set; }
        public Nullable<byte> Information79 { get; set; }
        public Nullable<byte> Information80 { get; set; }
        public Nullable<byte> Information81 { get; set; }
        public Nullable<byte> Information82 { get; set; }
        public Nullable<byte> Information83 { get; set; }
        public Nullable<byte> Information84 { get; set; }
        public Nullable<byte> Information85 { get; set; }
        public Nullable<byte> Information86 { get; set; }
        public Nullable<byte> Information87 { get; set; }
        public Nullable<byte> Information88 { get; set; }
        public Nullable<byte> Information89 { get; set; }
        public Nullable<byte> Information90 { get; set; }
        public Nullable<byte> Information91 { get; set; }
        public Nullable<byte> Information92 { get; set; }
        public Nullable<byte> Information93 { get; set; }
        public Nullable<byte> Information94 { get; set; }
        public Nullable<byte> Information95 { get; set; }
        public Nullable<byte> Information96 { get; set; }
        public Nullable<byte> Information97 { get; set; }
        public Nullable<byte> Information98 { get; set; }
        public Nullable<byte> Information99 { get; set; }
        public Nullable<byte> Information100 { get; set; }
        public Nullable<byte> Information101 { get; set; }
        public Nullable<byte> Information102 { get; set; }
        public Nullable<byte> Information103 { get; set; }
        public Nullable<byte> Information104 { get; set; }
        public Nullable<byte> Information105 { get; set; }
        public Nullable<byte> Information106 { get; set; }
        public Nullable<byte> Information107 { get; set; }
        public Nullable<int> BarCodeSolutionId { get; set; }
        public int id { get; set; }
        public Nullable<int> idVoucher { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
