//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_BOM
    {
        public string code { get; set; }
        public string name { get; set; }
        public string version { get; set; }
        public Nullable<decimal> produceQuantity { get; set; }
        public Nullable<decimal> rationWage { get; set; }
        public Nullable<decimal> rationCharge { get; set; }
        public Nullable<decimal> rationManHour { get; set; }
        public Nullable<byte> isDefaultBom { get; set; }
        public Nullable<int> bomDepth { get; set; }
        public Nullable<byte> disabled { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public string freeItem0 { get; set; }
        public string freeItem1 { get; set; }
        public string freeItem2 { get; set; }
        public string freeItem3 { get; set; }
        public string freeItem4 { get; set; }
        public string freeItem5 { get; set; }
        public string freeItem6 { get; set; }
        public string freeItem7 { get; set; }
        public string freeItem8 { get; set; }
        public string freeItem9 { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string priuserdefnvc5 { get; set; }
        public Nullable<decimal> priuserdefdecm5 { get; set; }
        public Nullable<decimal> producequantity2 { get; set; }
        public Nullable<decimal> rationcost { get; set; }
        public Nullable<decimal> rationmaterial { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> rateofexchange { get; set; }
        public Nullable<decimal> yieldrate { get; set; }
        public Nullable<byte> iscostbom { get; set; }
        public string idsaleorder { get; set; }
        public string maker { get; set; }
        public string auditor { get; set; }
        public string reviser { get; set; }
        public Nullable<byte> isorderbom { get; set; }
        public string customerName { get; set; }
        public string customerCode { get; set; }
        public string customerForShort { get; set; }
        public string pubuserdefnvc1 { get; set; }
        public string pubuserdefnvc2 { get; set; }
        public string pubuserdefnvc3 { get; set; }
        public string pubuserdefnvc4 { get; set; }
        public string pubuserdefnvc5 { get; set; }
        public string pubuserdefnvc6 { get; set; }
        public Nullable<decimal> pubuserdefdecm1 { get; set; }
        public Nullable<decimal> pubuserdefdecm2 { get; set; }
        public Nullable<decimal> pubuserdefdecm3 { get; set; }
        public Nullable<decimal> pubuserdefdecm4 { get; set; }
        public Nullable<decimal> pubuserdefdecm5 { get; set; }
        public Nullable<decimal> pubuserdefdecm6 { get; set; }
        public Nullable<decimal> priuserdefdecm6 { get; set; }
        public string priuserdefnvc6 { get; set; }
        public int id { get; set; }
        public Nullable<int> idBomRelationDTO { get; set; }
        public Nullable<int> idmanufactureplant { get; set; }
        public Nullable<int> idinventory { get; set; }
        public Nullable<int> idmechiner { get; set; }
        public Nullable<int> idrouting { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<int> idunit2 { get; set; }
        public Nullable<int> idwarehouse { get; set; }
        public Nullable<int> getbomchildunitmethod { get; set; }
        public Nullable<int> produceType { get; set; }
        public Nullable<int> voucherstate { get; set; }
        public Nullable<int> auditorid { get; set; }
        public Nullable<int> makerid { get; set; }
        public Nullable<System.DateTime> madeDate { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<System.DateTime> voucherdate { get; set; }
        public Nullable<System.DateTime> auditeddate { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
        public Nullable<int> reviserid { get; set; }
        public Nullable<System.DateTime> ReviserDate { get; set; }
    }
}
