//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_CashFlowItemClass_Ext
    {
        public string CashFlowItemClasscode_lev1 { get; set; }
        public string CashFlowItemClassname_lev1 { get; set; }
        public string CashFlowItemClasscode_lev2 { get; set; }
        public string CashFlowItemClassname_lev2 { get; set; }
        public string CashFlowItemClasscode_lev3 { get; set; }
        public string CashFlowItemClassname_lev3 { get; set; }
        public string CashFlowItemClasscode_lev4 { get; set; }
        public string CashFlowItemClassname_lev4 { get; set; }
        public string CashFlowItemClasscode_lev5 { get; set; }
        public string CashFlowItemClassname_lev5 { get; set; }
        public string CashFlowItemClasscode_lev6 { get; set; }
        public string CashFlowItemClassname_lev6 { get; set; }
        public string CashFlowItemClasscode_lev7 { get; set; }
        public string CashFlowItemClassname_lev7 { get; set; }
        public string CashFlowItemClasscode_lev8 { get; set; }
        public string CashFlowItemClassname_lev8 { get; set; }
        public string CashFlowItemClasscode_lev9 { get; set; }
        public string CashFlowItemClassname_lev9 { get; set; }
        public string CashFlowItemClasscode_lev10 { get; set; }
        public string CashFlowItemClassname_lev10 { get; set; }
        public string CashFlowItemClasscode_lev11 { get; set; }
        public string CashFlowItemClassname_lev11 { get; set; }
        public string CashFlowItemClasscode_lev12 { get; set; }
        public string CashFlowItemClassname_lev12 { get; set; }
        public string CashFlowItemClasscode_lev13 { get; set; }
        public string CashFlowItemClassname_lev13 { get; set; }
        public string CashFlowItemClasscode_lev14 { get; set; }
        public string CashFlowItemClassname_lev14 { get; set; }
        public string CashFlowItemClasscode_lev15 { get; set; }
        public string CashFlowItemClassname_lev15 { get; set; }
        public string depth { get; set; }
        public byte[] ts { get; set; }
        public Nullable<int> CashFlowItemClassid_lev1 { get; set; }
        public Nullable<int> CashFlowItemClassid_lev10 { get; set; }
        public Nullable<int> CashFlowItemClassid_lev11 { get; set; }
        public Nullable<int> CashFlowItemClassid_lev12 { get; set; }
        public Nullable<int> CashFlowItemClassid_lev13 { get; set; }
        public Nullable<int> CashFlowItemClassid_lev14 { get; set; }
        public Nullable<int> CashFlowItemClassid_lev15 { get; set; }
        public Nullable<int> CashFlowItemClassid_lev2 { get; set; }
        public Nullable<int> CashFlowItemClassid_lev3 { get; set; }
        public Nullable<int> CashFlowItemClassid_lev4 { get; set; }
        public Nullable<int> CashFlowItemClassid_lev5 { get; set; }
        public Nullable<int> CashFlowItemClassid_lev6 { get; set; }
        public Nullable<int> CashFlowItemClassid_lev7 { get; set; }
        public Nullable<int> CashFlowItemClassid_lev8 { get; set; }
        public Nullable<int> CashFlowItemClassid_lev9 { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
    }
}
