//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_DR_Store
    {
        public string code { get; set; }
        public string name { get; set; }
        public string abbreviation { get; set; }
        public string shorthand { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public Nullable<byte> disabled { get; set; }
        public string memo { get; set; }
        public string checkaddress { get; set; }
        public Nullable<int> cashshieldnum { get; set; }
        public Nullable<int> sequencenumber { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string priuserdefnvc5 { get; set; }
        public Nullable<decimal> priuserdefdecm5 { get; set; }
        public string autoLogistic { get; set; }
        public Nullable<byte> autoUnLock { get; set; }
        public Nullable<byte> nonPayNumber { get; set; }
        public Nullable<byte> paidNumber { get; set; }
        public Nullable<byte> haveSellerRemark { get; set; }
        public Nullable<byte> haveBuyerMessage { get; set; }
        public Nullable<byte> applyRefund { get; set; }
        public Nullable<byte> cashOnDeliveryOrder { get; set; }
        public Nullable<byte> paidOrderAutoCheck { get; set; }
        public Nullable<byte> wholesaleType { get; set; }
        public Nullable<byte> shipmentsAutoUpType { get; set; }
        public Nullable<byte> autoDownAddInvertory { get; set; }
        public Nullable<decimal> virtualInvertory { get; set; }
        public Nullable<byte> autoDownInventory { get; set; }
        public Nullable<decimal> upInventoryNumberPerce { get; set; }
        public string sellerNo { get; set; }
        public string shopWebset { get; set; }
        public string shopFullName { get; set; }
        public string correspondwarehouse { get; set; }
        public Nullable<byte> pickedUnLock { get; set; }
        public Nullable<byte> buyerAddressUpdate { get; set; }
        public Nullable<byte> isdeductionforepost { get; set; }
        public Nullable<int> idbankaccount { get; set; }
        public Nullable<int> iddepartment { get; set; }
        public Nullable<int> idmembertype { get; set; }
        public Nullable<int> iddefalutshipments { get; set; }
        public int id { get; set; }
        public Nullable<int> idinventoryclass { get; set; }
        public Nullable<int> idmarketingorgan { get; set; }
        public Nullable<int> idcustomer { get; set; }
        public Nullable<int> idsettlementcustomer { get; set; }
        public Nullable<int> idpartnerclass { get; set; }
        public Nullable<int> idperson { get; set; }
        public Nullable<int> idReceiveSettleStyle { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<int> iddistrict { get; set; }
        public Nullable<int> idwarehouse { get; set; }
        public Nullable<int> branchdistributionway { get; set; }
        public Nullable<int> storetype { get; set; }
        public Nullable<int> priceMode { get; set; }
        public Nullable<int> shopType { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<System.DateTime> LastRefundTime { get; set; }
    }
}
