//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_DR_MemberRetail
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<decimal> consumeamount { get; set; }
        public Nullable<decimal> integral { get; set; }
        public string memo { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string priuserdefnvc5 { get; set; }
        public Nullable<decimal> priuserdefdecm5 { get; set; }
        public string priuserdefnvc6 { get; set; }
        public Nullable<decimal> priuserdefdecm6 { get; set; }
        public string pubuserdefnvc1 { get; set; }
        public Nullable<decimal> pubuserdefdecm1 { get; set; }
        public string pubuserdefnvc2 { get; set; }
        public Nullable<decimal> pubuserdefdecm2 { get; set; }
        public string pubuserdefnvc3 { get; set; }
        public Nullable<decimal> pubuserdefdecm3 { get; set; }
        public string pubuserdefnvc4 { get; set; }
        public Nullable<decimal> pubuserdefdecm4 { get; set; }
        public string pubuserdefnvc5 { get; set; }
        public Nullable<decimal> pubuserdefdecm5 { get; set; }
        public string pubuserdefnvc6 { get; set; }
        public Nullable<decimal> pubuserdefdecm6 { get; set; }
        public Nullable<decimal> steadCashIntegral { get; set; }
        public string sysId { get; set; }
        public string mId { get; set; }
        public Nullable<decimal> storagesettleamount { get; set; }
        public Nullable<decimal> steadcashamount { get; set; }
        public Nullable<decimal> givechangeforstorageamount { get; set; }
        public string maker { get; set; }
        public Nullable<int> idbusitype { get; set; }
        public Nullable<int> iddepartment { get; set; }
        public Nullable<int> idmember { get; set; }
        public int id { get; set; }
        public Nullable<int> idstore { get; set; }
        public Nullable<int> IdMarketingOrgan { get; set; }
        public Nullable<int> idperson { get; set; }
        public Nullable<int> consumetype { get; set; }
        public Nullable<int> makerId { get; set; }
        public Nullable<long> retailid { get; set; }
        public Nullable<System.DateTime> voucherdate { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public string payordercode { get; set; }
    }
}
