//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_DR_MemberType_StorageRule
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<decimal> fullamount { get; set; }
        public Nullable<decimal> presentamount { get; set; }
        public Nullable<byte> isstorageintegral { get; set; }
        public Nullable<int> sequencenumber { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public Nullable<int> idMemberTypeDTO { get; set; }
        public int id { get; set; }
        public Nullable<int> storagetype { get; set; }
        public Nullable<System.DateTime> effectivedate { get; set; }
        public Nullable<System.DateTime> expirationdate { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
