//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_DR_MemberType
    {
        public string code { get; set; }
        public string name { get; set; }
        public string initpassword { get; set; }
        public Nullable<byte> isneedpwd { get; set; }
        public Nullable<int> validityperiod { get; set; }
        public Nullable<byte> isdiscount { get; set; }
        public Nullable<decimal> generaldiscountrate { get; set; }
        public Nullable<decimal> newprodiscountrate { get; set; }
        public Nullable<byte> isintegral { get; set; }
        public Nullable<decimal> initintegral { get; set; }
        public Nullable<byte> onlyinitpriceintegral { get; set; }
        public Nullable<decimal> generalamount { get; set; }
        public Nullable<decimal> generaiintegral { get; set; }
        public Nullable<decimal> newproamount { get; set; }
        public Nullable<decimal> newprointegral { get; set; }
        public Nullable<byte> ismonday { get; set; }
        public Nullable<byte> istuesday { get; set; }
        public Nullable<byte> iswednesday { get; set; }
        public Nullable<byte> isthursday { get; set; }
        public Nullable<byte> isfriday { get; set; }
        public Nullable<byte> issaturday { get; set; }
        public Nullable<byte> issunday { get; set; }
        public Nullable<decimal> weekdayintemulti { get; set; }
        public Nullable<decimal> memberbirthdayintemulti { get; set; }
        public Nullable<int> issystem { get; set; }
        public Nullable<int> sequencenumber { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public Nullable<byte> IsEndNode { get; set; }
        public string InId { get; set; }
        public string idparent { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string priuserdefnvc5 { get; set; }
        public Nullable<decimal> priuserdefdecm5 { get; set; }
        public byte isstorage { get; set; }
        public Nullable<decimal> canoveramount { get; set; }
        public Nullable<decimal> bottomamount { get; set; }
        public int id { get; set; }
        public Nullable<int> cardtype { get; set; }
        public Nullable<int> discounttype { get; set; }
        public Nullable<int> integraltype { get; set; }
        public Nullable<int> memberbirthdaytype { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
