//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class aa_DimensionSet
    {
        public string PriceSetType { get; set; }
        public Nullable<byte> Dimension { get; set; }
        public string Remark { get; set; }
        public Nullable<byte> IsInUse { get; set; }
        public byte[] TS { get; set; }
        public int id { get; set; }
    }
}
