//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_EcodeSeting
    {
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public string updatedby { get; set; }
        public byte[] ts { get; set; }
        public string CodingType { get; set; }
        public string prefixion0 { get; set; }
        public string prefixion1 { get; set; }
        public string prefixion2 { get; set; }
        public string prefixion3 { get; set; }
        public string prefixion4 { get; set; }
        public string prefixion5 { get; set; }
        public string prefixion6 { get; set; }
        public string prefixion7 { get; set; }
        public string prefixion8 { get; set; }
        public string prefixion9 { get; set; }
        public string prefixion10 { get; set; }
        public string Length0 { get; set; }
        public string Length1 { get; set; }
        public string Length2 { get; set; }
        public string Length3 { get; set; }
        public string Length4 { get; set; }
        public string Length5 { get; set; }
        public string Length6 { get; set; }
        public string Length7 { get; set; }
        public string Length8 { get; set; }
        public string Length9 { get; set; }
        public string Length10 { get; set; }
        public string InterceptMode { get; set; }
    }
}
