//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_Inventory
    {
        public string code { get; set; }
        public string name { get; set; }
        public string shorthand { get; set; }
        public string specification { get; set; }
        public Nullable<decimal> procureBatch { get; set; }
        public Nullable<decimal> invSCost { get; set; }
        public Nullable<decimal> latestCost { get; set; }
        public Nullable<decimal> avagCost { get; set; }
        public Nullable<byte> isLimitedWithdraw { get; set; }
        public Nullable<byte> isBatch { get; set; }
        public Nullable<byte> isQualityPeriod { get; set; }
        public Nullable<byte> isSale { get; set; }
        public Nullable<byte> isMadeSelf { get; set; }
        public Nullable<byte> isPurchase { get; set; }
        public Nullable<byte> isMaterial { get; set; }
        public Nullable<decimal> lowQuantity { get; set; }
        public Nullable<decimal> topQuantity { get; set; }
        public Nullable<decimal> safeQuantity { get; set; }
        public string picture { get; set; }
        public Nullable<byte> disabled { get; set; }
        public Nullable<byte> isQualityCheck { get; set; }
        public Nullable<byte> isMadeRequest { get; set; }
        public Nullable<byte> isSingleUnit { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public Nullable<byte> Userfreeitem7 { get; set; }
        public Nullable<byte> Userfreeitem6 { get; set; }
        public Nullable<byte> Userfreeitem2 { get; set; }
        public Nullable<byte> Userfreeitem1 { get; set; }
        public Nullable<byte> Userfreeitem9 { get; set; }
        public Nullable<byte> Userfreeitem0 { get; set; }
        public Nullable<byte> Userfreeitem8 { get; set; }
        public Nullable<byte> Userfreeitem5 { get; set; }
        public Nullable<byte> Userfreeitem4 { get; set; }
        public Nullable<byte> Userfreeitem3 { get; set; }
        public Nullable<byte> MustInputFreeitem7 { get; set; }
        public Nullable<byte> MustInputFreeitem2 { get; set; }
        public Nullable<byte> MustInputFreeitem6 { get; set; }
        public Nullable<byte> MustInputFreeitem3 { get; set; }
        public Nullable<byte> MustInputFreeitem5 { get; set; }
        public Nullable<byte> MustInputFreeitem4 { get; set; }
        public Nullable<byte> MustInputFreeitem9 { get; set; }
        public Nullable<byte> MustInputFreeitem1 { get; set; }
        public Nullable<byte> MustInputFreeitem8 { get; set; }
        public Nullable<byte> MustInputFreeitem0 { get; set; }
        public Nullable<decimal> produceBatch { get; set; }
        public string imageFile { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string priuserdefnvc5 { get; set; }
        public Nullable<decimal> priuserdefdecm5 { get; set; }
        public Nullable<decimal> standardturnoverdays { get; set; }
        public string HasEverChanged { get; set; }
        public Nullable<decimal> pickbatch { get; set; }
        public Nullable<byte> isphantom { get; set; }
        public Nullable<byte> ControlRangeFreeitem0 { get; set; }
        public Nullable<byte> ControlRangeFreeitem1 { get; set; }
        public Nullable<byte> ControlRangeFreeitem2 { get; set; }
        public Nullable<byte> ControlRangeFreeitem3 { get; set; }
        public Nullable<byte> ControlRangeFreeitem4 { get; set; }
        public Nullable<byte> ControlRangeFreeitem5 { get; set; }
        public Nullable<byte> ControlRangeFreeitem6 { get; set; }
        public Nullable<byte> ControlRangeFreeitem7 { get; set; }
        public Nullable<byte> ControlRangeFreeitem8 { get; set; }
        public Nullable<byte> ControlRangeFreeitem9 { get; set; }
        public Nullable<byte> IsLaborCost { get; set; }
        public Nullable<decimal> BatchRunNumber { get; set; }
        public Nullable<byte> IsNew { get; set; }
        public Nullable<System.DateTime> MadeRecordDate { get; set; }
        public string InventoryDescript { get; set; }
        public Nullable<int> ReNewGoodSellDays { get; set; }
        public Nullable<int> ReNewGoodAheadDays { get; set; }
        public Nullable<byte> IsSuite { get; set; }
        public Nullable<byte> IsWeigh { get; set; }
        public string DefaultBarCode { get; set; }
        public Nullable<int> NewProductPeriod { get; set; }
        public Nullable<int> Expired { get; set; }
        public Nullable<int> idbarcodesolution { get; set; }
        public int id { get; set; }
        public Nullable<int> idinventoryclass { get; set; }
        public Nullable<int> idinvlocation { get; set; }
        public Nullable<int> idMarketingOrgan { get; set; }
        public Nullable<int> idpartner { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<int> idunitbymanufacture { get; set; }
        public Nullable<int> idUnitByPurchase { get; set; }
        public Nullable<int> idUnitByRetail { get; set; }
        public Nullable<int> idUnitBySale { get; set; }
        public Nullable<int> idUnitByStock { get; set; }
        public Nullable<int> idunitgroup { get; set; }
        public Nullable<int> idSubUnitByReport { get; set; }
        public Nullable<int> ExpiredUnit { get; set; }
        public Nullable<int> idwarehouse { get; set; }
        public Nullable<int> customerReplenishmentRule { get; set; }
        public Nullable<int> pickbatchmethod { get; set; }
        public Nullable<int> planattribute { get; set; }
        public Nullable<int> productInfo { get; set; }
        public Nullable<int> storeReplenishmentRule { get; set; }
        public Nullable<int> taxRate { get; set; }
        public Nullable<int> unittype { get; set; }
        public Nullable<int> valueType { get; set; }
        public Nullable<System.DateTime> madeDate { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
        public string Creater { get; set; }
        public string Changer { get; set; }
        public Nullable<System.DateTime> Changedate { get; set; }
        public string JinShuiCode { get; set; }
        public Nullable<byte> IsModifiedCode { get; set; }
        public Nullable<byte> WithOutBargain { get; set; }
    }
}
