//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_IncDecWay_Ext
    {
        public string incDecWaycode_lev1 { get; set; }
        public string incDecWayname_lev1 { get; set; }
        public string incDecWaycode_lev2 { get; set; }
        public string incDecWayname_lev2 { get; set; }
        public string incDecWaycode_lev3 { get; set; }
        public string incDecWayname_lev3 { get; set; }
        public string incDecWaycode_lev4 { get; set; }
        public string incDecWayname_lev4 { get; set; }
        public string incDecWaycode_lev5 { get; set; }
        public string incDecWayname_lev5 { get; set; }
        public string incDecWaycode_lev6 { get; set; }
        public string incDecWayname_lev6 { get; set; }
        public string incDecWaycode_lev7 { get; set; }
        public string incDecWayname_lev7 { get; set; }
        public string incDecWaycode_lev8 { get; set; }
        public string incDecWayname_lev8 { get; set; }
        public string incDecWaycode_lev9 { get; set; }
        public string incDecWayname_lev9 { get; set; }
        public string incDecWaycode_lev10 { get; set; }
        public string incDecWayname_lev10 { get; set; }
        public string incDecWaycode_lev11 { get; set; }
        public string incDecWayname_lev11 { get; set; }
        public string incDecWaycode_lev12 { get; set; }
        public string incDecWayname_lev12 { get; set; }
        public string incDecWaycode_lev13 { get; set; }
        public string incDecWayname_lev13 { get; set; }
        public string incDecWaycode_lev14 { get; set; }
        public string incDecWayname_lev14 { get; set; }
        public string incDecWaycode_lev15 { get; set; }
        public string incDecWayname_lev15 { get; set; }
        public string depth { get; set; }
        public byte[] ts { get; set; }
        public int id { get; set; }
        public Nullable<int> incDecWayid_lev1 { get; set; }
        public Nullable<int> incDecWayid_lev10 { get; set; }
        public Nullable<int> incDecWayid_lev11 { get; set; }
        public Nullable<int> incDecWayid_lev12 { get; set; }
        public Nullable<int> incDecWayid_lev13 { get; set; }
        public Nullable<int> incDecWayid_lev14 { get; set; }
        public Nullable<int> incDecWayid_lev15 { get; set; }
        public Nullable<int> incDecWayid_lev2 { get; set; }
        public Nullable<int> incDecWayid_lev3 { get; set; }
        public Nullable<int> incDecWayid_lev4 { get; set; }
        public Nullable<int> incDecWayid_lev5 { get; set; }
        public Nullable<int> incDecWayid_lev6 { get; set; }
        public Nullable<int> incDecWayid_lev7 { get; set; }
        public Nullable<int> incDecWayid_lev8 { get; set; }
        public Nullable<int> incDecWayid_lev9 { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
    }
}
