//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_Position_Ext
    {
        public string positioncode_lev1 { get; set; }
        public string positionname_lev1 { get; set; }
        public string positioncode_lev2 { get; set; }
        public string positionname_lev2 { get; set; }
        public string positioncode_lev3 { get; set; }
        public string positionname_lev3 { get; set; }
        public string positioncode_lev4 { get; set; }
        public string positionname_lev4 { get; set; }
        public string positioncode_lev5 { get; set; }
        public string positionname_lev5 { get; set; }
        public string positioncode_lev6 { get; set; }
        public string positionname_lev6 { get; set; }
        public string positioncode_lev7 { get; set; }
        public string positionname_lev7 { get; set; }
        public string positioncode_lev8 { get; set; }
        public string positionname_lev8 { get; set; }
        public string positioncode_lev9 { get; set; }
        public string positionname_lev9 { get; set; }
        public string positioncode_lev10 { get; set; }
        public string positionname_lev10 { get; set; }
        public string positioncode_lev11 { get; set; }
        public string positionname_lev11 { get; set; }
        public string positioncode_lev12 { get; set; }
        public string positionname_lev12 { get; set; }
        public string positioncode_lev13 { get; set; }
        public string positionname_lev13 { get; set; }
        public string positioncode_lev14 { get; set; }
        public string positionname_lev14 { get; set; }
        public string positioncode_lev15 { get; set; }
        public string positionname_lev15 { get; set; }
        public string depth { get; set; }
        public byte[] ts { get; set; }
        public int id { get; set; }
        public Nullable<int> positionid_lev1 { get; set; }
        public Nullable<int> positionid_lev10 { get; set; }
        public Nullable<int> positionid_lev11 { get; set; }
        public Nullable<int> positionid_lev12 { get; set; }
        public Nullable<int> positionid_lev13 { get; set; }
        public Nullable<int> positionid_lev14 { get; set; }
        public Nullable<int> positionid_lev15 { get; set; }
        public Nullable<int> positionid_lev2 { get; set; }
        public Nullable<int> positionid_lev3 { get; set; }
        public Nullable<int> positionid_lev4 { get; set; }
        public Nullable<int> positionid_lev5 { get; set; }
        public Nullable<int> positionid_lev6 { get; set; }
        public Nullable<int> positionid_lev7 { get; set; }
        public Nullable<int> positionid_lev8 { get; set; }
        public Nullable<int> positionid_lev9 { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
    }
}
