//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_Project
    {
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] ts { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public byte disabled { get; set; }
        public Nullable<int> idMarketingOrgan { get; set; }
        public int id { get; set; }
        public Nullable<int> idclass { get; set; }
        public Nullable<System.DateTime> madeDate { get; set; }
    }
}
