//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_Person
    {
        public string code { get; set; }
        public string name { get; set; }
        public string shorthand { get; set; }
        public string nativePlace { get; set; }
        public string identityNo { get; set; }
        public string familyPhoneNo { get; set; }
        public string officePhoneNo { get; set; }
        public string mobilePhoneNo { get; set; }
        public string emailAddr { get; set; }
        public string qqcode { get; set; }
        public string msnAddr { get; set; }
        public string uuNo { get; set; }
        public string postCode { get; set; }
        public string postAddr { get; set; }
        public Nullable<byte> isSalesman { get; set; }
        public Nullable<decimal> creditDate { get; set; }
        public Nullable<decimal> creditQuantity { get; set; }
        public Nullable<decimal> aRBalance { get; set; }
        public Nullable<decimal> aPBalance { get; set; }
        public Nullable<byte> disabled { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string priuserdefnvc5 { get; set; }
        public Nullable<decimal> priuserdefdecm5 { get; set; }
        public Nullable<byte> IsNavigator { get; set; }
        public Nullable<byte> IsOperator { get; set; }
        public int id { get; set; }
        public Nullable<int> iddepartment { get; set; }
        public Nullable<int> idMarketingOrgan { get; set; }
        public Nullable<int> education { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> identificationType { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<System.DateTime> madeDate { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
    }
}
