//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_StoreInventoryPrice
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<decimal> MemberPrice { get; set; }
        public Nullable<decimal> retailPriceNew { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public string StoreRetailPriceFormula { get; set; }
        public string StoreRetailPrice { get; set; }
        public string StoreMemberPrice { get; set; }
        public string StoreMemberPriceFormula { get; set; }
        public string PriceKey { get; set; }
        public Nullable<int> SearchFlag { get; set; }
        public string InvBarCode { get; set; }
        public Nullable<int> idstore { get; set; }
        public Nullable<int> idinventory { get; set; }
        public int id { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<int> dimension { get; set; }
        public Nullable<int> iddepartment { get; set; }
        public Nullable<int> iddistrict { get; set; }
        public Nullable<int> StoreType { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    }
}
