//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_UseStatus_Ext
    {
        public string useStatuscode_lev1 { get; set; }
        public string useStatusname_lev1 { get; set; }
        public string useStatuscode_lev2 { get; set; }
        public string useStatusname_lev2 { get; set; }
        public string useStatuscode_lev3 { get; set; }
        public string useStatusname_lev3 { get; set; }
        public string useStatuscode_lev4 { get; set; }
        public string useStatusname_lev4 { get; set; }
        public string useStatuscode_lev5 { get; set; }
        public string useStatusname_lev5 { get; set; }
        public string useStatuscode_lev6 { get; set; }
        public string useStatusname_lev6 { get; set; }
        public string useStatuscode_lev7 { get; set; }
        public string useStatusname_lev7 { get; set; }
        public string useStatuscode_lev8 { get; set; }
        public string useStatusname_lev8 { get; set; }
        public string useStatuscode_lev9 { get; set; }
        public string useStatusname_lev9 { get; set; }
        public string useStatuscode_lev10 { get; set; }
        public string useStatusname_lev10 { get; set; }
        public string useStatuscode_lev11 { get; set; }
        public string useStatusname_lev11 { get; set; }
        public string useStatuscode_lev12 { get; set; }
        public string useStatusname_lev12 { get; set; }
        public string useStatuscode_lev13 { get; set; }
        public string useStatusname_lev13 { get; set; }
        public string useStatuscode_lev14 { get; set; }
        public string useStatusname_lev14 { get; set; }
        public string useStatuscode_lev15 { get; set; }
        public string useStatusname_lev15 { get; set; }
        public string depth { get; set; }
        public byte[] ts { get; set; }
        public int id { get; set; }
        public Nullable<int> useStatusid_lev1 { get; set; }
        public Nullable<int> useStatusid_lev10 { get; set; }
        public Nullable<int> useStatusid_lev11 { get; set; }
        public Nullable<int> useStatusid_lev12 { get; set; }
        public Nullable<int> useStatusid_lev13 { get; set; }
        public Nullable<int> useStatusid_lev14 { get; set; }
        public Nullable<int> useStatusid_lev15 { get; set; }
        public Nullable<int> useStatusid_lev2 { get; set; }
        public Nullable<int> useStatusid_lev3 { get; set; }
        public Nullable<int> useStatusid_lev4 { get; set; }
        public Nullable<int> useStatusid_lev5 { get; set; }
        public Nullable<int> useStatusid_lev6 { get; set; }
        public Nullable<int> useStatusid_lev7 { get; set; }
        public Nullable<int> useStatusid_lev8 { get; set; }
        public Nullable<int> useStatusid_lev9 { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
    }
}
