//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_UseStatus
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<byte> depth { get; set; }
        public string inid { get; set; }
        public Nullable<byte> isendnode { get; set; }
        public Nullable<byte> ispreset { get; set; }
        public byte[] ts { get; set; }
        public Nullable<byte> isDepr { get; set; }
        public Nullable<byte> Disabled { get; set; }
        public int id { get; set; }
        public Nullable<int> idparent { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
    }
}
