//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AM_HandleVoucherDept
    {
        public string Code { get; set; }
        public Nullable<int> DeptVer { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<byte> IsMain { get; set; }
        public byte[] ts { get; set; }
        public Nullable<int> iduseDept { get; set; }
        public Nullable<int> IDHandleVoucherDetailDTO { get; set; }
        public int id { get; set; }
    }
}
