//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARAP_OriginalAmount
    {
        public string reviser { get; set; }
        public Nullable<byte> isCarriedForwardOut { get; set; }
        public Nullable<byte> isCarriedForwardIn { get; set; }
        public byte[] ts { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
        public bool ifAccountClear { get; set; }
    }
}
