//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2B_InventoryClassUploadLog
    {
        public int id { get; set; }
        public Nullable<int> idInventoryClass { get; set; }
        public string B2BInventoryClassCode { get; set; }
        public byte[] inventoryClassTS { get; set; }
        public Nullable<System.DateTime> uploadDate { get; set; }
    }
}
