//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2B_Sku
    {
        public int Id { get; set; }
        public long SkuId { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public string InventoryCode { get; set; }
        public string UnitNameBySale { get; set; }
        public Nullable<int> IdUnitBySale { get; set; }
        public string FreeItem0 { get; set; }
        public string FreeItem1 { get; set; }
        public string FreeItem2 { get; set; }
        public string FreeItem3 { get; set; }
        public string FreeItem4 { get; set; }
        public string FreeItem5 { get; set; }
        public string FreeItem6 { get; set; }
        public string FreeItem7 { get; set; }
        public string FreeItem8 { get; set; }
        public string FreeItem9 { get; set; }
        public System.DateTime CreateTime { get; set; }
        public byte[] TS { get; set; }
    }
}
