//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_CashCheckVoucher
    {
        public string code { get; set; }
        public Nullable<decimal> origRealAmount { get; set; }
        public Nullable<decimal> origAccountAmount { get; set; }
        public Nullable<decimal> origProfitLossAmount { get; set; }
        public Nullable<decimal> profitLossAmount { get; set; }
        public Nullable<decimal> exchange { get; set; }
        public string docid { get; set; }
        public string memo { get; set; }
        public string maker { get; set; }
        public string auditor { get; set; }
        public string reviser { get; set; }
        public Nullable<byte> iscarriedforwardout { get; set; }
        public Nullable<byte> iscarriedforwardin { get; set; }
        public Nullable<byte> ismodifiedcode { get; set; }
        public byte[] ts { get; set; }
        public string priuserdefnvc1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public string priuserdefnvc5 { get; set; }
        public string priuserdefnvc6 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public Nullable<decimal> priuserdefdecm5 { get; set; }
        public Nullable<decimal> priuserdefdecm6 { get; set; }
        public string pubuserdefnvc1 { get; set; }
        public string pubuserdefnvc2 { get; set; }
        public string pubuserdefnvc3 { get; set; }
        public string pubuserdefnvc4 { get; set; }
        public string pubuserdefnvc5 { get; set; }
        public string pubuserdefnvc6 { get; set; }
        public Nullable<decimal> pubuserdefdecm1 { get; set; }
        public Nullable<decimal> pubuserdefdecm2 { get; set; }
        public Nullable<decimal> pubuserdefdecm3 { get; set; }
        public Nullable<decimal> pubuserdefdecm4 { get; set; }
        public Nullable<decimal> pubuserdefdecm5 { get; set; }
        public Nullable<decimal> pubuserdefdecm6 { get; set; }
        public int PrintCount { get; set; }
        public int ID { get; set; }
        public Nullable<int> idbankaccount { get; set; }
        public Nullable<int> IdMarketingOrgan { get; set; }
        public Nullable<int> idperson { get; set; }
        public Nullable<int> checkState { get; set; }
        public Nullable<int> voucherstate { get; set; }
        public Nullable<int> auditorid { get; set; }
        public Nullable<int> makerid { get; set; }
        public Nullable<System.DateTime> voucherdate { get; set; }
        public Nullable<System.DateTime> madedate { get; set; }
        public Nullable<System.DateTime> auditeddate { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    }
}
