//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_IncomeVoucher_b
    {
        public string code { get; set; }
        public Nullable<decimal> origTaxAmount { get; set; }
        public Nullable<decimal> origTax { get; set; }
        public Nullable<decimal> origamount { get; set; }
        public Nullable<decimal> taxExchange { get; set; }
        public Nullable<decimal> taxamount { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> origSettleAmount { get; set; }
        public Nullable<decimal> settleAmount { get; set; }
        public Nullable<byte> isTax { get; set; }
        public Nullable<byte> ismodifyorigtax { get; set; }
        public byte[] ts { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string pubuserdefnvc1 { get; set; }
        public Nullable<decimal> pubuserdefdecm1 { get; set; }
        public string pubuserdefnvc2 { get; set; }
        public Nullable<decimal> pubuserdefdecm2 { get; set; }
        public string pubuserdefnvc3 { get; set; }
        public Nullable<decimal> pubuserdefdecm3 { get; set; }
        public string pubuserdefnvc4 { get; set; }
        public Nullable<decimal> pubuserdefdecm4 { get; set; }
        public int ID { get; set; }
        public Nullable<int> idincomeitem { get; set; }
        public Nullable<int> idproject { get; set; }
        public Nullable<int> idIncomeVoucherDTO { get; set; }
        public Nullable<int> saleOrderDetailId { get; set; }
    }
}
