//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_NoteCommonInfo
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string NoteID { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> ImgLogoID { get; set; }
        public Nullable<int> ImgTypeID { get; set; }
        public Nullable<int> PosIndex { get; set; }
    }
}
