//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_NotePrintList
    {
        public int ID { get; set; }
        public int InfoID { get; set; }
        public string PartName { get; set; }
        public int DataType { get; set; }
        public string DataValue { get; set; }
        public string SubTableColName { get; set; }
        public Nullable<int> SubTableRowNum { get; set; }
        public string SubTableName { get; set; }
    }
}
