//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_NotePrintFilter
    {
        public int ID { get; set; }
        public string NoteID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> DateType { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string UserIDList { get; set; }
        public string HostList { get; set; }
        public Nullable<int> UseRegion { get; set; }
        public Nullable<int> HaveCancel { get; set; }
        public Nullable<int> SubConfig { get; set; }
        public string SourceType { get; set; }
    }
}
