//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_PrinterParam
    {
        public int ID { get; set; }
        public string NoteID { get; set; }
        public string PrinterName { get; set; }
        public string DriverName { get; set; }
        public string HostName { get; set; }
        public Nullable<int> PrintOrient { get; set; }
        public Nullable<double> PrintX { get; set; }
        public Nullable<double> PrintY { get; set; }
        public Nullable<int> PaperMode { get; set; }
        public string PaperName { get; set; }
        public Nullable<int> PaperSize { get; set; }
        public Nullable<int> PaperAlign { get; set; }
        public Nullable<int> PrintType { get; set; }
        public Nullable<int> MicroAdjust { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
