//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DI_RRAInventory
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> AvailableQuantity { get; set; }
        public Nullable<decimal> ReplenishmentRuleTotalQuantity { get; set; }
        public byte[] Ts { get; set; }
        public Nullable<decimal> RequestTotalQuantity { get; set; }
        public string freeItem0 { get; set; }
        public string freeItem1 { get; set; }
        public string freeItem2 { get; set; }
        public string freeItem3 { get; set; }
        public string freeItem4 { get; set; }
        public string freeItem5 { get; set; }
        public string freeItem6 { get; set; }
        public string freeItem7 { get; set; }
        public string freeItem8 { get; set; }
        public string freeItem9 { get; set; }
        public Nullable<int> ReNewGoodSellDays { get; set; }
        public Nullable<int> ReNewGoodAheadDays { get; set; }
        public int ID { get; set; }
        public Nullable<int> idinventory { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<int> idoutWarehouse { get; set; }
        public Nullable<int> idStoreWarehouseReplenishmentRule { get; set; }
        public Nullable<int> idCustormerReplenishmentRule { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    }
}
