//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DI_RunShopTarget
    {
        public byte[] ts { get; set; }
        public Nullable<byte> isReportSalesQuantity { get; set; }
        public Nullable<byte> isReportStockQuantity { get; set; }
        public Nullable<byte> isOrderedDirect { get; set; }
        public Nullable<byte> isSignInPhoto { get; set; }
        public Nullable<byte> isSignOutPhoto { get; set; }
        public Nullable<byte> isPromotionPhoto { get; set; }
        public Nullable<byte> isCompetitionPhoto { get; set; }
        public int targetType { get; set; }
        public string code { get; set; }
        public string mapMark { get; set; }
        public int id { get; set; }
        public Nullable<int> idStore { get; set; }
        public Nullable<int> idPartner { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
