//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DI_RRASourceRelation
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public byte[] Ts { get; set; }
        public Nullable<decimal> Quantity2 { get; set; }
        public string SourceVoucherCode { get; set; }
        public string SourceVoucherTs { get; set; }
        public string SourceVoucherDetailTs { get; set; }
        public Nullable<decimal> changerate { get; set; }
        public int ID { get; set; }
        public Nullable<int> idcurrency { get; set; }
        public Nullable<int> idproject { get; set; }
        public Nullable<int> IdUnit { get; set; }
        public Nullable<int> IdUnit2 { get; set; }
        public Nullable<int> idRRAStoreCustormerDTO { get; set; }
        public Nullable<int> SourceVoucherID { get; set; }
        public Nullable<int> SourceVoucherDetailID { get; set; }
        public Nullable<int> idsourceVoucherType { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
    }
}
