//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DI_RRAOption
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<byte> ProcuremenEarlyDays { get; set; }
        public Nullable<byte> FIDivided { get; set; }
        public byte[] Ts { get; set; }
        public Nullable<byte> ExistedQuantity { get; set; }
        public Nullable<byte> PurchasereQuisition { get; set; }
        public Nullable<byte> PurchasereQuisitionWithUnAudit { get; set; }
        public Nullable<byte> PurchaseOrderOnWay { get; set; }
        public Nullable<byte> PurchaseOrderOnWayWithUnAudit { get; set; }
        public Nullable<byte> PurchaseArrival { get; set; }
        public Nullable<byte> PurchaseReceive { get; set; }
        public Nullable<byte> TransOnWay { get; set; }
        public Nullable<byte> OtherOnWay { get; set; }
        public Nullable<byte> ProductReceive { get; set; }
        public Nullable<byte> ProduceOnWay { get; set; }
        public Nullable<byte> SafeStock { get; set; }
        public Nullable<byte> LowStock { get; set; }
        public Nullable<byte> SaleOrder { get; set; }
        public Nullable<byte> SaleOrderWithUnAudit { get; set; }
        public Nullable<byte> SaleDelivery { get; set; }
        public Nullable<byte> SaleDispatch { get; set; }
        public Nullable<byte> TransDIspatch { get; set; }
        public Nullable<byte> OtherDispatch { get; set; }
        public Nullable<byte> MaterialDispatch { get; set; }
        public Nullable<byte> ProduceDispatch { get; set; }
        public Nullable<byte> UseDateTimeAvailableQuantity { get; set; }
        public Nullable<byte> ProduceOnWayWithUnAudit { get; set; }
        public Nullable<byte> ProduceDispatchWithUnAudit { get; set; }
        public Nullable<byte> WithEmptyWarhouse { get; set; }
        public Nullable<byte> Store_ExistedQuantity { get; set; }
        public Nullable<byte> Store_PurchaseArrival { get; set; }
        public Nullable<byte> Store_PurchaseReceive { get; set; }
        public Nullable<byte> Store_TransOnWay { get; set; }
        public Nullable<byte> Store_OtherOnWay { get; set; }
        public Nullable<byte> Store_SafeStock { get; set; }
        public Nullable<byte> Store_LowStock { get; set; }
        public Nullable<byte> Store_SaleDelivery { get; set; }
        public Nullable<byte> Store_SaleDispatch { get; set; }
        public Nullable<byte> Store_TransDIspatch { get; set; }
        public Nullable<byte> Store_OtherDispatch { get; set; }
        public Nullable<byte> Store_StockRequestQuantity { get; set; }
        public Nullable<byte> Store_StockRequestQuantityWithNoAudit { get; set; }
        public Nullable<byte> Store_ESStoreForDispatchQuantity { get; set; }
        public Nullable<byte> Store_ESStoreForDispatchQuantityNoAudit { get; set; }
        public Nullable<byte> StockRequest { get; set; }
        public Nullable<byte> StockRequestWithUnAudit { get; set; }
        public Nullable<byte> DistributionForSendQuantity { get; set; }
        public Nullable<byte> DistributionForReceiveQuantity { get; set; }
        public int ID { get; set; }
        public Nullable<int> idoutWarehouse { get; set; }
        public Nullable<System.DateTime> PreAvailableQuantityDate { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
