//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_metadata
    {
        public long doc_type_id { get; set; }
        public string doc_type_name { get; set; }
        public string gen_doc_tree_sp_name { get; set; }
        public string get_carry_over_list_sp_name { get; set; }
        public string table_name { get; set; }
        public string column_name { get; set; }
    }
}
