//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAP_Template
    {
        public string GroupName { get; set; }
        public string voucherInfoName { get; set; }
        public string Title { get; set; }
        public int DisposalType { get; set; }
        public int IndexOrder { get; set; }
        public bool IsExport { get; set; }
        public bool IsImport { get; set; }
        public bool IsSearch { get; set; }
        public bool IsSystem { get; set; }
        public string Description { get; set; }
        public string ExpressionName { get; set; }
        public int id { get; set; }
        public int voucherInfoID { get; set; }
    }
}
