//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAP_UserDefineArticleDTO_0002
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] ts { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string madeDate { get; set; }
        public Nullable<int> idClass { get; set; }
        public Nullable<byte> disabled { get; set; }
        public Nullable<decimal> col17 { get; set; }
    }
}
