//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eap_UserDefineItems
    {
        public string FieldName { get; set; }
        public int Type { get; set; }
        public string Title { get; set; }
        public string Expression { get; set; }
        public string EnumName { get; set; }
        public int MaxLength { get; set; }
        public string RefDTOName { get; set; }
        public string FieldType { get; set; }
        public string RefLinkField { get; set; }
        public bool AllowNone { get; set; }
        public bool EditReadOnly { get; set; }
        public bool Visible { get; set; }
        public bool beUsed { get; set; }
        public string UserPrompt { get; set; }
        public string VoucherIDs { get; set; }
        public string VoucherNames { get; set; }
        public int OrderNum { get; set; }
        public Nullable<short> Precision { get; set; }
        public int ID { get; set; }
    }
}
