//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eap_PrintDataColumn
    {
        public byte[] ts { get; set; }
        public string name { get; set; }
        public string Title { get; set; }
        public string DataType { get; set; }
        public string DynPropertyString { get; set; }
        public Nullable<int> PosLeft { get; set; }
        public int id { get; set; }
        public Nullable<int> IdPrintDataTable { get; set; }
    }
}
