//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eap_wfnode
    {
        public string Title { get; set; }
        public int AuditType { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public Nullable<int> PositionX { get; set; }
        public Nullable<int> PositionY { get; set; }
        public Nullable<byte> CanFinal { get; set; }
        public Nullable<int> NodeType { get; set; }
        public Nullable<int> MailRuleID { get; set; }
        public Nullable<int> FinalConditionPlanID { get; set; }
        public int id { get; set; }
        public Nullable<int> SolutionID { get; set; }
        public Nullable<int> MsgRuleID { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
