//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAP_ReportMatrixColumnSort
    {
        public int id { get; set; }
        public string groupItemColumnName { get; set; }
        public int idSearchPlan { get; set; }
        public string refDto { get; set; }
        public byte sortType { get; set; }
        public Nullable<int> idDto { get; set; }
        public Nullable<int> showIndex { get; set; }
        public System.DateTime createdTime { get; set; }
    }
}
