//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eap_syncfileinfo
    {
        public string posmaxts { get; set; }
        public string maxts { get; set; }
        public string posOtherMaxts { get; set; }
        public string maxOtherts { get; set; }
        public string filepath { get; set; }
        public string reqpos { get; set; }
        public int datatype { get; set; }
        public byte[] ts { get; set; }
        public string filename { get; set; }
        public string accnum { get; set; }
        public string BapType { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> makedate { get; set; }
    }
}
