//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eap_PrintDataTable
    {
        public byte[] ts { get; set; }
        public string name { get; set; }
        public string DetailType { get; set; }
        public string ParentDetail { get; set; }
        public Nullable<int> FixRows { get; set; }
        public Nullable<byte> PrintPageTotal { get; set; }
        public Nullable<byte> FillBlankRows { get; set; }
        public Nullable<byte> RowsAdaptive { get; set; }
        public Nullable<byte> PrintTotal { get; set; }
        public Nullable<byte> PrintPageSubTotal { get; set; }
        public string DynPropertyString { get; set; }
        public Nullable<int> PosTop { get; set; }
        public Nullable<int> PosBottom { get; set; }
        public int id { get; set; }
        public Nullable<int> IdPrintTemplate { get; set; }
    }
}
