//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAP_VoucherQueryConfig
    {
        public int id { get; set; }
        public string bizCode { get; set; }
        public string serviceType { get; set; }
        public string dtoname { get; set; }
        public string tablename { get; set; }
        public string detailDtoName { get; set; }
        public string detailTableName { get; set; }
        public string detailRefMainTableFieldName { get; set; }
        public string fixedWhereExpression { get; set; }
    }
}
