//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAP_User
    {
        public string Code { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public string password { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public Nullable<bool> isStoped { get; set; }
        public string mobile { get; set; }
        public Nullable<byte> AuthState { get; set; }
        public string PersonName { get; set; }
        public byte[] ts { get; set; }
        public string Memo { get; set; }
        public Nullable<bool> issystem { get; set; }
        public byte ShowNewFuncIntro { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public int id { get; set; }
        public Nullable<int> IdMarketingOrgan { get; set; }
        public Nullable<int> IdPerson { get; set; }
        public Nullable<System.DateTime> lastLoginDate { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<byte> ActorType { get; set; }
        public Nullable<bool> IsHeadQuarters { get; set; }
        public string ExpressionName { get; set; }
        public string CloudUserId { get; set; }
        public Nullable<byte> UpgradePwdState { get; set; }
        public string DuduPhone { get; set; }
        public Nullable<bool> IsDemo { get; set; }
    }
}
