//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eap_ReportCommonData
    {
        public string ReportName { get; set; }
        public int DisplayStyle { get; set; }
        public bool IsShowFontPage { get; set; }
        public bool IsShowOtherPage { get; set; }
        public bool ShowPageHeaderPage { get; set; }
        public bool ShowPageFooterPage { get; set; }
        public string columnConfigFlag { get; set; }
        public int ItemID { get; set; }
    }
}
