//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eap_externalaccountbinding
    {
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public string name { get; set; }
        public string Source { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string UserId { get; set; }
        public string DogId { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
