//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eap_FreeItems
    {
        public string Name { get; set; }
        public string Title { get; set; }
        public bool beUsed { get; set; }
        public string FieldType { get; set; }
        public string EnumName { get; set; }
        public string RefObject { get; set; }
        public string ValueFrom { get; set; }
        public string ValueConcrete { get; set; }
        public int MaxLength { get; set; }
        public bool AllowNull { get; set; }
        public bool AllowEdit { get; set; }
        public string DefaultValue { get; set; }
        public int Width { get; set; }
        public bool Visible { get; set; }
        public string Vouchers { get; set; }
        public bool Apply { get; set; }
        public bool AutoAdd { get; set; }
        public int ID { get; set; }
    }
}
