//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eap_UserDefineArticleColumn
    {
        public byte[] ts { get; set; }
        public string name { get; set; }
        public string Title { get; set; }
        public string FieldType { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> ColPrecision { get; set; }
        public string FormatString { get; set; }
        public Nullable<byte> IsNotNull { get; set; }
        public Nullable<byte> IsAllowEdit { get; set; }
        public Nullable<byte> IsDisplayInData { get; set; }
        public Nullable<byte> IsDisplayInSet { get; set; }
        public Nullable<byte> IsDefault { get; set; }
        public Nullable<byte> IsSystem { get; set; }
        public Nullable<byte> IsDisabled { get; set; }
        public Nullable<byte> IsPrimaryKey { get; set; }
        public string DefaultValue { get; set; }
        public string RefDTOName { get; set; }
        public string RefDTOProperty { get; set; }
        public string EnumName { get; set; }
        public string RefTitle { get; set; }
        public string RePage { get; set; }
        public Nullable<int> ColPos { get; set; }
        public string ValueFrom { get; set; }
        public string ControlType { get; set; }
        public int id { get; set; }
        public string FieldName { get; set; }
        public string RefWhere { get; set; }
        public string ExpressionName { get; set; }
        public Nullable<int> idEnum { get; set; }
        public int ArticleDictId { get; set; }
        public Nullable<System.DateTime> MadeDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
