//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAP_MessageBox
    {
        public string UserId { get; set; }
        public bool IsUnread { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> Direction { get; set; }
        public int Id { get; set; }
        public int MessageId { get; set; }
    }
}
