//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAP_ReportRelationEntity
    {
        public byte[] ts { get; set; }
        public string ReportName { get; set; }
        public string EntityName { get; set; }
        public string JoinType { get; set; }
        public string JoinWhere { get; set; }
        public Nullable<byte> IsMainEntity { get; set; }
        public string TableName { get; set; }
        public string EntityTitle { get; set; }
        public string RelationEntity { get; set; }
        public string RelationOption { get; set; }
        public string OptionValue { get; set; }
        public Nullable<int> IsMainVoucher { get; set; }
        public Nullable<int> UnionSection { get; set; }
        public string DTOName { get; set; }
        public Nullable<int> BusinessType { get; set; }
        public Nullable<byte> IsEndNode { get; set; }
        public int id { get; set; }
        public Nullable<int> EntityType { get; set; }
        public Nullable<int> idparent { get; set; }
        public Nullable<int> ideap_reporttemplate { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
