//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAP_VoucherQueryConfigQueryField
    {
        public int id { get; set; }
        public string bizCode { get; set; }
        public string FieldExpression { get; set; }
        public string ExpressionAlias { get; set; }
        public string fieldType { get; set; }
        public string LeftJoinRightTableName { get; set; }
        public string LeftJoinRightExpressName { get; set; }
        public string LeftJoinLeftExpressName { get; set; }
        public Nullable<int> ExpressNameOrder { get; set; }
        public Nullable<bool> istotal { get; set; }
        public Nullable<bool> isDetail { get; set; }
        public string groupByFieldName { get; set; }
        public string fieldComments { get; set; }
    }
}
