//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAP_SearchItemCtrlInfo_Ext
    {
        public string DtoName { get; set; }
        public string RefPage { get; set; }
        public string RefAddPage { get; set; }
        public string RefWhere { get; set; }
        public string EnumName { get; set; }
        public Nullable<int> Status { get; set; }
        public string ValueType { get; set; }
        public Nullable<bool> AllowEdit { get; set; }
        public string DropDownStyle { get; set; }
        public string DropDownPanelID { get; set; }
        public string ControlType { get; set; }
        public string DropDownWhere { get; set; }
        public string RefDataSource { get; set; }
        public Nullable<int> Precision { get; set; }
        public Nullable<int> MaxLength { get; set; }
        public Nullable<bool> PropTitleCanChange { get; set; }
        public string SelectButtonItems { get; set; }
        public string onClientClick { get; set; }
        public Nullable<int> PrefixCheckCtrlStyle { get; set; }
        public string RefShowField { get; set; }
        public byte[] ts { get; set; }
        public string ExpressionName { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string PrefixCheckCtrlStylename { get; set; }
        public int ItemId { get; set; }
        public int id { get; set; }
        public Nullable<int> MultiSelect { get; set; }
    }
}
