//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eap_VoucherWebControls
    {
        public string Name { get; set; }
        public string Text { get; set; }
        public Nullable<int> Left { get; set; }
        public Nullable<int> Top { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string ControlType { get; set; }
        public string Parent { get; set; }
        public string DynPropertyString { get; set; }
        public byte[] ts { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public int id { get; set; }
    }
}
