//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eap_MBColumnSetSolution
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string DtoName { get; set; }
        public string BizCode { get; set; }
        public string separatorStr { get; set; }
        public string assemblyClass { get; set; }
        public string assemblyName { get; set; }
        public string SourceColumnSetSolutionName { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public byte[] Ts { get; set; }
    }
}
