//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eap_WorkPlanForm_User
    {
        public string Code { get; set; }
        public int OrderIndex { get; set; }
        public string Type { get; set; }
        public string SolutionName { get; set; }
        public Nullable<bool> MustSelect { get; set; }
        public bool Visible { get; set; }
        public string UserID { get; set; }
        public bool isSystem { get; set; }
        public int ID { get; set; }
    }
}
