//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eap_VoucherControls
    {
        public string Name { get; set; }
        public string Title { get; set; }
        public string TabPageName { get; set; }
        public string LabelID { get; set; }
        public string ControlID { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> AddReadOnly { get; set; }
        public Nullable<bool> EditReadOnly { get; set; }
        public string ControlType { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public Nullable<int> Left { get; set; }
        public Nullable<int> Top { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> TabIndex { get; set; }
        public Nullable<int> CtlIndex { get; set; }
        public Nullable<bool> AllowZero { get; set; }
        public Nullable<bool> AllowNone { get; set; }
        public string DefaultValue { get; set; }
        public string Format { get; set; }
        public string Expression { get; set; }
        public Nullable<short> MaxLength { get; set; }
        public Nullable<short> Precision { get; set; }
        public Nullable<short> MaxShowLen { get; set; }
        public string EnumName { get; set; }
        public string RefPage { get; set; }
        public string RefDTOName { get; set; }
        public string RefShowField { get; set; }
        public string RefLinkField { get; set; }
        public string UserCheck { get; set; }
        public string UserPrompt { get; set; }
        public Nullable<bool> IsUserDef { get; set; }
        public Nullable<bool> AllowUserDef { get; set; }
        public Nullable<bool> AllowUserDelete { get; set; }
        public string RefDataSource { get; set; }
        public Nullable<bool> ShowSysField { get; set; }
        public string DropDownStyle { get; set; }
        public string DropDownPanelID { get; set; }
        public string OriginalTitle { get; set; }
        public string SysPropValue { get; set; }
        public Nullable<short> Mustshow { get; set; }
        public Nullable<short> AutoReDeploy { get; set; }
        public string DynPropertyString { get; set; }
        public int id { get; set; }
        public Nullable<bool> RecordValue { get; set; }
        public byte[] TS { get; set; }
        public string ExpressionName { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string ExpressionTips { get; set; }
        public Nullable<int> VoucherFieldType { get; set; }
        public int VoucherID { get; set; }
        public Nullable<bool> RequiredControl { get; set; }
        public string InputControlType { get; set; }
    }
}
