//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eap_designDTOLog
    {
        public string DtoName { get; set; }
        public string tablename { get; set; }
        public string sqltext { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public byte[] ts { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public int ID { get; set; }
        public Nullable<int> idDTO { get; set; }
    }
}
