//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eap_reporttemplate
    {
        public string title { get; set; }
        public string name { get; set; }
        public Nullable<byte> reportType { get; set; }
        public string menuCode { get; set; }
        public string dbsql { get; set; }
        public Nullable<byte> reportStyle { get; set; }
        public int id { get; set; }
        public string MainEntity { get; set; }
        public Nullable<byte> IsHasChart { get; set; }
        public Nullable<byte> IsToggleFilter { get; set; }
        public Nullable<byte> IsMatrixSum { get; set; }
        public Nullable<byte> IsHasDynCol { get; set; }
        public string ExpressionName { get; set; }
        public Nullable<int> TFlag { get; set; }
        public byte[] ts { get; set; }
        public Nullable<int> DisplayStyle { get; set; }
        public Nullable<int> NegativeFormat { get; set; }
        public Nullable<int> ReportTypeNew { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
