//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eap_reporttablecol
    {
        public string title { get; set; }
        public string fieldName { get; set; }
        public string selectFieldName { get; set; }
        public Nullable<byte> mustDisplay { get; set; }
        public Nullable<byte> canDisplay { get; set; }
        public byte Display { get; set; }
        public int ShowIndex { get; set; }
        public byte FixedHeader { get; set; }
        public byte TotalSum { get; set; }
        public Nullable<int> CanSum { get; set; }
        public byte UserSort { get; set; }
        public Nullable<double> width { get; set; }
        public string style { get; set; }
        public string format { get; set; }
        public string linkurl { get; set; }
        public string BundleField { get; set; }
        public Nullable<byte> IsMain { get; set; }
        public Nullable<byte> IsHeader { get; set; }
        public string OriginalTitle { get; set; }
        public Nullable<int> SqlSort { get; set; }
        public string outputValue { get; set; }
        public string dtoprop { get; set; }
        public string RefDtoProp { get; set; }
        public string linkTitle { get; set; }
        public string tooltip { get; set; }
        public Nullable<byte> isbundle { get; set; }
        public Nullable<byte> IsDynamicCol { get; set; }
        public Nullable<byte> isFormatCtrlBySys { get; set; }
        public string GroupOutputValue { get; set; }
        public string FootOutputValue { get; set; }
        public Nullable<byte> hideZeroValue { get; set; }
        public Nullable<int> dataType { get; set; }
        public Nullable<byte> isGather { get; set; }
        public Nullable<int> titleAlign { get; set; }
        public Nullable<int> bodyAlign { get; set; }
        public int id { get; set; }
        public Nullable<byte> IsShowChart { get; set; }
        public Nullable<byte> IsNegNumShowSign { get; set; }
        public string outputTitle { get; set; }
        public string ExpressionName { get; set; }
        public Nullable<byte> CanVRatio { get; set; }
        public Nullable<byte> CanHRatio { get; set; }
        public Nullable<byte> IsVRatio { get; set; }
        public Nullable<byte> IsHRatio { get; set; }
        public Nullable<byte> IsRefBaseInfoCol { get; set; }
        public Nullable<int> TFlag { get; set; }
        public string ControlledKey { get; set; }
        public byte[] ts { get; set; }
        public string name { get; set; }
        public Nullable<int> ideap_reportsolution { get; set; }
        public Nullable<int> idparent { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string FootOutputSql { get; set; }
    }
}
