//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eap_PrintSetting
    {
        public byte[] ts { get; set; }
        public string name { get; set; }
        public Nullable<byte> PrintAllPage { get; set; }
        public string PrintPageRange { get; set; }
        public Nullable<int> PageCopies { get; set; }
        public Nullable<int> PageVouchers { get; set; }
        public Nullable<byte> PrintSeparator { get; set; }
        public Nullable<int> CopiesSpacing { get; set; }
        public Nullable<byte> Collated { get; set; }
        public string DynPropertyString { get; set; }
        public int id { get; set; }
    }
}
