//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eap_idesktopappitem
    {
        public byte[] ts { get; set; }
        public string name { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string Description { get; set; }
        public string MenuCode { get; set; }
        public string LinkUrl { get; set; }
        public int id { get; set; }
        public Nullable<int> AppSourceType { get; set; }
        public Nullable<int> AppType { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> Seq { get; set; }
    }
}
