//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eap_attachmentinfo
    {
        public string TemplateName { get; set; }
        public string DTOProp { get; set; }
        public string AssociateID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public byte[] FileContent { get; set; }
        public long FileSize { get; set; }
        public string UploadPath { get; set; }
        public string Creater { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> DownloadCount { get; set; }
        public byte[] TS { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
