//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eap_EditTableColumn
    {
        public string Name { get; set; }
        public string Title { get; set; }
        public string EnumName { get; set; }
        public string RefPage { get; set; }
        public string RefDtoName { get; set; }
        public string RefShowField { get; set; }
        public string RefLinkField { get; set; }
        public string UserCheck { get; set; }
        public string UserPrompt { get; set; }
        public Nullable<byte> IsUserDef { get; set; }
        public Nullable<byte> AllowUserDef { get; set; }
        public Nullable<byte> AllowUserDelete { get; set; }
        public string FixedValue { get; set; }
        public Nullable<int> ColIndex { get; set; }
        public string DropDownStyle { get; set; }
        public string DropDownPanelID { get; set; }
        public string SysPropValue { get; set; }
        public Nullable<int> MustShow { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public string ColumnType { get; set; }
        public string Format { get; set; }
        public string Expression { get; set; }
        public Nullable<byte> MonetaryAmountInWords { get; set; }
        public Nullable<byte> AllowSorting { get; set; }
        public Nullable<int> SortDirection { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<int> DefineLevel { get; set; }
        public Nullable<byte> ShowSysField { get; set; }
        public string refDataSource { get; set; }
        public string OriginalTitle { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<byte> IsI18NField { get; set; }
        public Nullable<byte> Visible { get; set; }
        public Nullable<byte> ReadOnly { get; set; }
        public Nullable<byte> AllowNull { get; set; }
        public Nullable<byte> AllowZero { get; set; }
        public Nullable<int> MaxLength { get; set; }
        public Nullable<int> Precision { get; set; }
        public Nullable<byte> AllowTotal { get; set; }
        public Nullable<byte> Sizeable { get; set; }
        public Nullable<byte> AddCopyData { get; set; }
        public string DynPropertyString { get; set; }
        public int ID { get; set; }
        public string ExpressionName { get; set; }
        public byte[] ts { get; set; }
        public Nullable<int> TableID { get; set; }
    }
}
