//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAP_HoldFunctionAuth
    {
        public string menucode { get; set; }
        public string name { get; set; }
        public Nullable<bool> isusergroup { get; set; }
        public byte[] ts { get; set; }
        public string Tag { get; set; }
        public int id { get; set; }
        public Nullable<int> idfunctionauth { get; set; }
        public Nullable<int> idactor { get; set; }
    }
}
