//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eap_MenuTree
    {
        public string Title { get; set; }
        public Nullable<int> ShowIndex { get; set; }
        public Nullable<bool> isSystem { get; set; }
        public string inId { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> TFlag { get; set; }
        public Nullable<byte> IsEndNode { get; set; }
        public int id { get; set; }
        public Nullable<int> parentID { get; set; }
        public string ExpressionName { get; set; }
    }
}
