//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eap_DTO
    {
        public string Name { get; set; }
        public string Title { get; set; }
        public string TableName { get; set; }
        public string ClassName { get; set; }
        public string NameField { get; set; }
        public string CodeField { get; set; }
        public string memo { get; set; }
        public int id { get; set; }
        public byte[] ts { get; set; }
        public Nullable<int> TFlag { get; set; }
        public string Code { get; set; }
        public Nullable<int> IDPackage { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string AssemblyName { get; set; }
    }
}
