//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAP_SearchPlanInfo_Ext
    {
        public string SearchName { get; set; }
        public int SearchStyle { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public string PlanName { get; set; }
        public Nullable<int> MaxItemCount { get; set; }
        public Nullable<bool> IsDirectSearch { get; set; }
        public Nullable<bool> IsPublicPlan { get; set; }
        public Nullable<int> LayoutStyle { get; set; }
        public Nullable<int> LayoutColumnCount { get; set; }
        public int id { get; set; }
        public byte[] ts { get; set; }
        public Nullable<bool> IsShowExpression { get; set; }
        public string Expression { get; set; }
        public Nullable<bool> Isdisplay { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<bool> EndGrade { get; set; }
        public Nullable<int> TFlag { get; set; }
        public string NoDelete { get; set; }
        public string ExpressionName { get; set; }
        public int SearchId { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
