//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAP_AuthControl
    {
        public Nullable<int> dataauthtype { get; set; }
        public Nullable<bool> iscontrol { get; set; }
        public Nullable<int> controltype { get; set; }
        public byte[] ts { get; set; }
        public int id { get; set; }
        public Nullable<int> archivesid { get; set; }
        public Nullable<int> idactor { get; set; }
    }
}
