//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAP_AppUserAssociation
    {
        public string AppUserID { get; set; }
        public string AppUserName { get; set; }
        public byte[] ts { get; set; }
        public string AccessToken { get; set; }
        public string RefreshToken { get; set; }
        public Nullable<System.DateTime> ExpiredTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<byte> IsAdmin { get; set; }
        public string BindState { get; set; }
        public int id { get; set; }
        public int AppID { get; set; }
        public int UserID { get; set; }
    }
}
