//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_Doc
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<decimal> accuorigamountdr { get; set; }
        public Nullable<decimal> accuorigamountcr { get; set; }
        public Nullable<decimal> accuamountdr { get; set; }
        public Nullable<decimal> accuamountcr { get; set; }
        public Nullable<byte> iscashieraudit { get; set; }
        public string cashiername { get; set; }
        public Nullable<byte> ispost { get; set; }
        public string bookkeepername { get; set; }
        public Nullable<byte> iserror { get; set; }
        public Nullable<byte> isinvalidate { get; set; }
        public string invalidatorname { get; set; }
        public Nullable<byte> iscashflowed { get; set; }
        public Nullable<byte> isquantitydoc { get; set; }
        public Nullable<byte> isforeigncurrencydoc { get; set; }
        public Nullable<int> attachedvouchernum { get; set; }
        public Nullable<int> accountingperiod { get; set; }
        public Nullable<int> accountingyear { get; set; }
        public string maker { get; set; }
        public string auditor { get; set; }
        public string reviser { get; set; }
        public Nullable<byte> iscarriedforwardout { get; set; }
        public Nullable<byte> iscarriedforwardin { get; set; }
        public Nullable<byte> ismodifiedcode { get; set; }
        public byte[] ts { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string priuserdefnvc5 { get; set; }
        public Nullable<decimal> priuserdefdecm5 { get; set; }
        public string priuserdefnvc6 { get; set; }
        public Nullable<decimal> priuserdefdecm6 { get; set; }
        public Nullable<byte> isCashierDoc { get; set; }
        public string DocOrderNum { get; set; }
        public string SourceType { get; set; }
        public string SourceContent { get; set; }
        public int PrintCount { get; set; }
        public Nullable<byte> isCashflowByHand { get; set; }
        public string externalCode { get; set; }
        public Nullable<decimal> businessDocMoney { get; set; }
        public Nullable<System.DateTime> batch { get; set; }
        public int id { get; set; }
        public Nullable<int> iddoctype { get; set; }
        public Nullable<int> isdefrence { get; set; }
        public Nullable<int> cashflowedstate { get; set; }
        public Nullable<int> docbusinesstype { get; set; }
        public Nullable<int> docsourcetype { get; set; }
        public Nullable<int> invalidateState { get; set; }
        public Nullable<int> makeErrorState { get; set; }
        public Nullable<int> voucherstate { get; set; }
        public Nullable<int> tempDocGenerate { get; set; }
        public Nullable<int> auditorid { get; set; }
        public Nullable<int> makerid { get; set; }
        public Nullable<int> bookkeeperid { get; set; }
        public Nullable<int> cashierid { get; set; }
        public Nullable<int> invalidatorid { get; set; }
        public Nullable<int> idperiod { get; set; }
        public string transDocId { get; set; }
        public Nullable<System.DateTime> cashierauditdate { get; set; }
        public Nullable<System.DateTime> postdate { get; set; }
        public Nullable<System.DateTime> invalidatedate { get; set; }
        public Nullable<System.DateTime> voucherdate { get; set; }
        public Nullable<System.DateTime> madedate { get; set; }
        public Nullable<System.DateTime> auditeddate { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    }
}
