//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_MultiColumnSet
    {
        public Nullable<byte> isBalanceMultiColumn { get; set; }
        public byte[] ts { get; set; }
        public int id { get; set; }
        public Nullable<int> idanalysisaccount { get; set; }
        public Nullable<int> multicolumnsetanalysiscontent { get; set; }
        public Nullable<int> multicolumnsetanalysismethod { get; set; }
        public Nullable<int> searchplanid { get; set; }
        public Nullable<int> userid { get; set; }
    }
}
