//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_ReferenceAuxiliaryInfo
    {
        public string code { get; set; }
        public string billno { get; set; }
        public string bizno { get; set; }
        public byte[] ts { get; set; }
        public Nullable<decimal> exchangerate { get; set; }
        public int id { get; set; }
        public Nullable<int> idbankAccount { get; set; }
        public Nullable<int> idauxAccDepartment { get; set; }
        public Nullable<int> idauxAccInventory { get; set; }
        public Nullable<int> idauxAccCustomer { get; set; }
        public Nullable<int> idauxAccSupplier { get; set; }
        public Nullable<int> idauxAccPerson { get; set; }
        public Nullable<int> idclerk { get; set; }
        public Nullable<int> idauxAccProject { get; set; }
        public Nullable<int> idsettlestyle { get; set; }
        public Nullable<int> idexauxacc1 { get; set; }
        public Nullable<int> idexauxacc10 { get; set; }
        public Nullable<int> idexauxacc2 { get; set; }
        public Nullable<int> idexauxacc3 { get; set; }
        public Nullable<int> idexauxacc4 { get; set; }
        public Nullable<int> idexauxacc5 { get; set; }
        public Nullable<int> idexauxacc6 { get; set; }
        public Nullable<int> idexauxacc7 { get; set; }
        public Nullable<int> idexauxacc8 { get; set; }
        public Nullable<int> idexauxacc9 { get; set; }
        public Nullable<int> ReferenceDocId { get; set; }
        public Nullable<int> idReferenceEntryDTO { get; set; }
        public Nullable<System.DateTime> billdate { get; set; }
        public Nullable<System.DateTime> bizdate { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
    }
}
