//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_SalesCostTransform_Details
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> idSalesCostTransFormDTO { get; set; }
        public Nullable<int> IdDetailStockAccount { get; set; }
        public Nullable<int> IdDetailCostAccount { get; set; }
        public Nullable<int> IdDetailIncomeAccount { get; set; }
        public Nullable<int> IdUnit { get; set; }
        public Nullable<int> IdAuxInventory { get; set; }
        public Nullable<int> IdAuxProject { get; set; }
        public Nullable<int> IdAuxPerson { get; set; }
        public Nullable<int> IdAuxPartner { get; set; }
        public Nullable<int> IdAuxDepartment { get; set; }
        public Nullable<int> idExAuxAcc1 { get; set; }
        public Nullable<int> idExAuxAcc2 { get; set; }
        public Nullable<int> idExAuxAcc3 { get; set; }
        public Nullable<int> idExAuxAcc4 { get; set; }
        public Nullable<int> idExAuxAcc5 { get; set; }
        public Nullable<int> idExAuxAcc6 { get; set; }
        public Nullable<int> idExAuxAcc7 { get; set; }
        public Nullable<int> idExAuxAcc8 { get; set; }
        public Nullable<int> idExAuxAcc9 { get; set; }
        public Nullable<int> idExAuxAcc10 { get; set; }
        public Nullable<decimal> saleAmountCr { get; set; }
        public Nullable<decimal> saleQuantityCr { get; set; }
        public Nullable<decimal> stockAmount { get; set; }
        public Nullable<decimal> stockQuantity { get; set; }
        public Nullable<decimal> transFormQuantity { get; set; }
        public Nullable<decimal> transFormPrice { get; set; }
        public Nullable<decimal> transFormAmount { get; set; }
        public byte[] ts { get; set; }
    }
}
