//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_WriteOffJournal
    {
        public string bizno { get; set; }
        public Nullable<decimal> origamount { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> writeoffedorigamount { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> writeoffedamount { get; set; }
        public Nullable<decimal> writeoffableorigamount { get; set; }
        public Nullable<decimal> writeoffableamount { get; set; }
        public Nullable<byte> iscarriedforwardout { get; set; }
        public Nullable<byte> iscarriedforwardin { get; set; }
        public byte[] ts { get; set; }
        public string summary { get; set; }
        public string docno { get; set; }
        public string billNo { get; set; }
        public int id { get; set; }
        public Nullable<int> idaccount { get; set; }
        public int idcurrency { get; set; }
        public Nullable<int> idauxAccDepartment { get; set; }
        public Nullable<int> iddocType { get; set; }
        public Nullable<int> idauxAccInventory { get; set; }
        public Nullable<int> idauxAccCustomer { get; set; }
        public Nullable<int> idauxAccPerson { get; set; }
        public Nullable<int> idclerk { get; set; }
        public Nullable<int> idauxaccproject { get; set; }
        public Nullable<int> dcdirection { get; set; }
        public Nullable<int> writeoffjournaltype { get; set; }
        public Nullable<int> idauxperiodbegindetail { get; set; }
        public Nullable<int> idexauxacc1 { get; set; }
        public Nullable<int> idexauxacc10 { get; set; }
        public Nullable<int> idexauxacc2 { get; set; }
        public Nullable<int> idexauxacc3 { get; set; }
        public Nullable<int> idexauxacc4 { get; set; }
        public Nullable<int> idexauxacc5 { get; set; }
        public Nullable<int> idexauxacc6 { get; set; }
        public Nullable<int> idexauxacc7 { get; set; }
        public Nullable<int> idexauxacc8 { get; set; }
        public Nullable<int> idexauxacc9 { get; set; }
        public Nullable<int> idjournal { get; set; }
        public Nullable<System.DateTime> docmadedate { get; set; }
        public Nullable<System.DateTime> bizdate { get; set; }
        public Nullable<System.DateTime> billDate { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
    }
}
