//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvCostAnalysisRpt20
    {
        public int id { get; set; }
        public Nullable<decimal> finalamount { get; set; }
        public Nullable<decimal> finalQuantity { get; set; }
        public string AnalysisType { get; set; }
        public string ResultType { get; set; }
        public Nullable<decimal> RefValue { get; set; }
        public Nullable<decimal> CostVolatility { get; set; }
    }
}
