//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ME_MemberStorageDetail_b
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<decimal> totalstorageamount { get; set; }
        public Nullable<decimal> balancetotalstorage { get; set; }
        public Nullable<decimal> thisstorageamount { get; set; }
        public Nullable<decimal> thispresentamount { get; set; }
        public Nullable<decimal> thisvalidstorageamount { get; set; }
        public Nullable<decimal> fullamount { get; set; }
        public string storagedetails { get; set; }
        public Nullable<int> sequencenumber { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public Nullable<decimal> AfterBalanceStorage { get; set; }
        public int id { get; set; }
        public Nullable<int> idmember { get; set; }
        public Nullable<int> idmembertype { get; set; }
        public Nullable<int> idmembertypebefore { get; set; }
        public Nullable<int> storagetype { get; set; }
        public Nullable<int> idMemberStorageDTO { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string pubuserdefnvc1 { get; set; }
        public Nullable<decimal> pubuserdefdecm1 { get; set; }
        public string pubuserdefnvc2 { get; set; }
        public Nullable<decimal> pubuserdefdecm2 { get; set; }
        public string pubuserdefnvc3 { get; set; }
        public Nullable<decimal> pubuserdefdecm3 { get; set; }
        public string pubuserdefnvc4 { get; set; }
        public Nullable<decimal> pubuserdefdecm4 { get; set; }
    }
}
