//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_Available
    {
        public Nullable<decimal> PurchaseOrderOnWayQuantity { get; set; }
        public Nullable<decimal> PurchaseArrivalQuantity { get; set; }
        public Nullable<decimal> PurchaseForReceiveQuantity { get; set; }
        public Nullable<decimal> OnProducingQuantity { get; set; }
        public Nullable<decimal> ProductForReceiveQuantity { get; set; }
        public Nullable<decimal> ExistingQuantity { get; set; }
        public Nullable<decimal> PurchaseRequisitionQuantity { get; set; }
        public Nullable<decimal> OtherOnWayQuantity { get; set; }
        public Nullable<decimal> TransOnWayQuantity { get; set; }
        public Nullable<decimal> ForSaleOrderQuantity { get; set; }
        public Nullable<decimal> SaleDeliveryQuantity { get; set; }
        public Nullable<decimal> ForSaleDispatchQuantity { get; set; }
        public Nullable<decimal> ProduceForDispatchQuantity { get; set; }
        public Nullable<decimal> MaterialForSendQuantity { get; set; }
        public Nullable<decimal> SafeLowQuantity { get; set; }
        public Nullable<decimal> OtherForDispatchQuantity { get; set; }
        public Nullable<decimal> TransForDispatchQuantity { get; set; }
        public Nullable<decimal> ForStockOrderQuantity { get; set; }
        public int IdSku { get; set; }
    }
}
