//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_CostAllocationDirectMaterialSumOrder_b
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> nassignedquantity { get; set; }
        public Nullable<decimal> nassignedcost { get; set; }
        public Nullable<decimal> assignedquantity { get; set; }
        public Nullable<decimal> assignedcost { get; set; }
        public Nullable<decimal> balancequantity { get; set; }
        public Nullable<decimal> balancecost { get; set; }
        public Nullable<decimal> origassignedquantity { get; set; }
        public Nullable<decimal> totalassignedquantity { get; set; }
        public Nullable<int> sequencenumber { get; set; }
        public Nullable<decimal> ckcost { get; set; }
        public byte[] ts { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string pubuserdefnvc1 { get; set; }
        public Nullable<decimal> pubuserdefdecm1 { get; set; }
        public string pubuserdefnvc2 { get; set; }
        public Nullable<decimal> pubuserdefdecm2 { get; set; }
        public string pubuserdefnvc3 { get; set; }
        public Nullable<decimal> pubuserdefdecm3 { get; set; }
        public string pubuserdefnvc4 { get; set; }
        public Nullable<decimal> pubuserdefdecm4 { get; set; }
        public int id { get; set; }
        public Nullable<int> idinventory { get; set; }
        public Nullable<int> idbaseunit { get; set; }
        public Nullable<int> idCostAllocationDirectMaterialSumOrderDTO { get; set; }
        public Nullable<int> ManufactureOrderMaterialDetailId { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    }
}
