//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_IntendSaleOrder_b
    {
        public string code { get; set; }
        public string name { get; set; }
        public string compositionQuantity { get; set; }
        public string inventoryBarCode { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> quantity2 { get; set; }
        public Nullable<decimal> baseQuantity { get; set; }
        public Nullable<decimal> subQuantity { get; set; }
        public Nullable<decimal> unitExchangeRate { get; set; }
        public string bomType { get; set; }
        public string bomVersion { get; set; }
        public Nullable<byte> hasMRP { get; set; }
        public Nullable<byte> hasPRA { get; set; }
        public Nullable<int> totalMRPCount { get; set; }
        public Nullable<int> totalPRACount { get; set; }
        public Nullable<decimal> totalManufactureQuantity { get; set; }
        public Nullable<decimal> totalManufactureQuantity2 { get; set; }
        public Nullable<decimal> totalPurchaseQuantity { get; set; }
        public Nullable<decimal> totalPurchaseQuantity2 { get; set; }
        public Nullable<decimal> totalExecutedQuantity { get; set; }
        public Nullable<decimal> totalExecutedQuantity2 { get; set; }
        public Nullable<int> sequenceNumber { get; set; }
        public byte[] ts { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string pubuserdefnvc1 { get; set; }
        public Nullable<decimal> pubuserdefdecm1 { get; set; }
        public string pubuserdefnvc2 { get; set; }
        public Nullable<decimal> pubuserdefdecm2 { get; set; }
        public string pubuserdefnvc3 { get; set; }
        public Nullable<decimal> pubuserdefdecm3 { get; set; }
        public string pubuserdefnvc4 { get; set; }
        public Nullable<decimal> pubuserdefdecm4 { get; set; }
        public string freeItem0 { get; set; }
        public string freeItem1 { get; set; }
        public string freeItem2 { get; set; }
        public string freeItem3 { get; set; }
        public string freeItem4 { get; set; }
        public string freeItem5 { get; set; }
        public string freeItem6 { get; set; }
        public string freeItem7 { get; set; }
        public string freeItem8 { get; set; }
        public string freeItem9 { get; set; }
        public int ID { get; set; }
        public Nullable<int> bomId { get; set; }
        public Nullable<int> idbom { get; set; }
        public Nullable<int> idinventory { get; set; }
        public Nullable<int> idproject { get; set; }
        public Nullable<int> idbaseunit { get; set; }
        public Nullable<int> idsubunit { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<int> idunit2 { get; set; }
        public Nullable<int> idIntendSaleOrderDTO { get; set; }
        public Nullable<System.DateTime> demandingDate { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
    }
}
