//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_ManufactureOrder_b
    {
        public string code { get; set; }
        public string name { get; set; }
        public string inventoryBarCode { get; set; }
        public string sourceVoucherCode { get; set; }
        public string bomType { get; set; }
        public string bomVersion { get; set; }
        public string batch { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> unitExchangeRate { get; set; }
        public Nullable<decimal> quantity2 { get; set; }
        public Nullable<decimal> wholeSuitMaterialQuantity { get; set; }
        public Nullable<decimal> totalStockInQuantity { get; set; }
        public Nullable<decimal> TotalStockInQuantity2 { get; set; }
        public Nullable<decimal> totalCheckedAccount { get; set; }
        public Nullable<decimal> totalCheckedQuantity { get; set; }
        public Nullable<byte> hasPRA { get; set; }
        public Nullable<int> totalpracount { get; set; }
        public Nullable<int> totalStockCount { get; set; }
        public string saleOrderCode { get; set; }
        public string isNoModify { get; set; }
        public Nullable<decimal> baseQuantity { get; set; }
        public Nullable<decimal> subQuantity { get; set; }
        public Nullable<byte> fulfillCostFlag { get; set; }
        public Nullable<int> sequencenumber { get; set; }
        public byte[] ts { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string pubuserdefnvc1 { get; set; }
        public Nullable<decimal> pubuserdefdecm1 { get; set; }
        public string pubuserdefnvc2 { get; set; }
        public Nullable<decimal> pubuserdefdecm2 { get; set; }
        public string pubuserdefnvc3 { get; set; }
        public Nullable<decimal> pubuserdefdecm3 { get; set; }
        public string pubuserdefnvc4 { get; set; }
        public Nullable<decimal> pubuserdefdecm4 { get; set; }
        public string freeItem0 { get; set; }
        public string freeItem1 { get; set; }
        public string freeItem2 { get; set; }
        public string freeItem3 { get; set; }
        public string freeItem4 { get; set; }
        public string freeItem5 { get; set; }
        public string freeItem6 { get; set; }
        public string freeItem7 { get; set; }
        public string freeItem8 { get; set; }
        public string freeItem9 { get; set; }
        public int id { get; set; }
        public Nullable<int> idbom { get; set; }
        public Nullable<int> bomId { get; set; }
        public Nullable<int> idinventory { get; set; }
        public Nullable<int> idcustomer { get; set; }
        public Nullable<int> idproject { get; set; }
        public Nullable<int> idrouting { get; set; }
        public Nullable<int> idbaseunit { get; set; }
        public Nullable<int> idsubunit { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<int> idunit2 { get; set; }
        public Nullable<int> idwarehouse { get; set; }
        public Nullable<int> bomExpandType { get; set; }
        public Nullable<int> finishState { get; set; }
        public Nullable<int> processState { get; set; }
        public Nullable<int> sourcecondition { get; set; }
        public Nullable<int> sourceVoucherId { get; set; }
        public Nullable<int> sourceVoucherDetailId { get; set; }
        public Nullable<int> idManufactureOrderDTO { get; set; }
        public Nullable<int> saleOrderId { get; set; }
        public Nullable<int> saleOrderDetailId { get; set; }
        public Nullable<int> idsourcevouchertype { get; set; }
        public Nullable<System.DateTime> preStartDate { get; set; }
        public Nullable<System.DateTime> preFinishDate { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    }
}
