//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_OperationSku
    {
        public Nullable<int> InvLev { get; set; }
        public Nullable<decimal> availableQuantity { get; set; }
        public Nullable<decimal> grossDemand { get; set; }
        public Nullable<decimal> actualDemand { get; set; }
        public Nullable<decimal> suggestionQuantity { get; set; }
        public Nullable<decimal> openingQuantity { get; set; }
        public Nullable<byte> IsComputed { get; set; }
        public Nullable<decimal> ClosingQuantity { get; set; }
        public Nullable<byte> UnitType { get; set; }
        public Nullable<decimal> unitExchangeRate { get; set; }
        public Nullable<decimal> requiredquantity { get; set; }
        public Nullable<decimal> produceQuantity { get; set; }
        public Nullable<decimal> ProcureBatch { get; set; }
        public Nullable<decimal> YieldRate { get; set; }
        public Nullable<decimal> WasteRate { get; set; }
        public Nullable<byte> IsEnd { get; set; }
        public Nullable<decimal> pickbatch { get; set; }
        public Nullable<byte> IsMadeSelf { get; set; }
        public Nullable<byte> IsMadeRequest { get; set; }
        public Nullable<byte> IsPurchase { get; set; }
        public string code { get; set; }
        public string computevoucherCode { get; set; }
        public string freeItem0 { get; set; }
        public string freeItem1 { get; set; }
        public string freeItem2 { get; set; }
        public string freeItem3 { get; set; }
        public string freeItem4 { get; set; }
        public string freeItem5 { get; set; }
        public string freeItem6 { get; set; }
        public string freeItem7 { get; set; }
        public string freeItem8 { get; set; }
        public string freeItem9 { get; set; }
        public int ID { get; set; }
        public Nullable<int> idBom { get; set; }
        public Nullable<int> IdBomRelationParent { get; set; }
        public Nullable<int> idbomchild { get; set; }
        public Nullable<int> idBomRelation { get; set; }
        public Nullable<int> IdInventory { get; set; }
        public Nullable<int> idBaseUnit { get; set; }
        public Nullable<int> idSourceDetailId { get; set; }
        public Nullable<int> planattribute { get; set; }
        public Nullable<int> idComputeVoucher { get; set; }
        public Nullable<int> IdSku { get; set; }
        public Nullable<int> idSourceVoucherType { get; set; }
        public Nullable<System.DateTime> demandingDate { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    }
}
