//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_PRA_PurSuggestion2PurRequisition
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<decimal> currentquantity2 { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> taxRate { get; set; }
        public Nullable<decimal> taxPrice { get; set; }
        public Nullable<decimal> currentquantity { get; set; }
        public Nullable<decimal> unitexchangerate { get; set; }
        public Nullable<int> sequencenumber { get; set; }
        public byte[] ts { get; set; }
        public string isNoModify { get; set; }
        public string freeItem0 { get; set; }
        public string freeItem1 { get; set; }
        public string freeItem2 { get; set; }
        public string freeItem3 { get; set; }
        public string freeItem4 { get; set; }
        public string freeItem5 { get; set; }
        public string freeItem6 { get; set; }
        public string freeItem7 { get; set; }
        public string freeItem8 { get; set; }
        public string freeItem9 { get; set; }
        public int id { get; set; }
        public Nullable<int> iddepartment { get; set; }
        public Nullable<int> idinventory { get; set; }
        public Nullable<int> idpartner { get; set; }
        public Nullable<int> idclerk { get; set; }
        public Nullable<int> idproject { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<int> idunit2 { get; set; }
        public Nullable<int> iduser { get; set; }
        public Nullable<int> idpurchasesuggestion { get; set; }
        public Nullable<System.DateTime> purchasedate { get; set; }
        public Nullable<System.DateTime> demanddate { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    }
}
