//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_PRA_PraResult
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<decimal> topQuantity { get; set; }
        public string sourceVoucherCode { get; set; }
        public string saleOrderCode { get; set; }
        public Nullable<decimal> grossDemand { get; set; }
        public Nullable<decimal> actualDemand { get; set; }
        public Nullable<decimal> actualDemand2 { get; set; }
        public Nullable<decimal> existingQuantity { get; set; }
        public Nullable<decimal> lowquantity { get; set; }
        public Nullable<decimal> safeQuantity { get; set; }
        public Nullable<decimal> purchaseRequisitionQuantity { get; set; }
        public Nullable<decimal> purchaseOnWayQuantity { get; set; }
        public Nullable<decimal> onProducingQuantity { get; set; }
        public Nullable<decimal> transOnWayQuantity { get; set; }
        public Nullable<decimal> otherOnWayQuantity { get; set; }
        public Nullable<decimal> saleDeliveryQuantity { get; set; }
        public Nullable<decimal> manufactureMaterialsQuantity { get; set; }
        public Nullable<decimal> transForDispatchQuantity { get; set; }
        public Nullable<decimal> otherForDispatchQuantity { get; set; }
        public Nullable<decimal> suggestionQuantity { get; set; }
        public Nullable<decimal> suggestionQuantity2 { get; set; }
        public Nullable<decimal> unitExchangeRate { get; set; }
        public Nullable<int> sortno { get; set; }
        public Nullable<int> mergetype { get; set; }
        public Nullable<decimal> openingquantity { get; set; }
        public Nullable<decimal> closingquantity { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> availablequantity { get; set; }
        public Nullable<decimal> tempbatchaq { get; set; }
        public Nullable<int> sequencenumber { get; set; }
        public byte[] ts { get; set; }
        public Nullable<decimal> tempOpeningQuantity { get; set; }
        public Nullable<decimal> tempClosingQuantity { get; set; }
        public string freeItem0 { get; set; }
        public string freeItem1 { get; set; }
        public string freeItem2 { get; set; }
        public string freeItem3 { get; set; }
        public string freeItem4 { get; set; }
        public string freeItem5 { get; set; }
        public string freeItem6 { get; set; }
        public string freeItem7 { get; set; }
        public string freeItem8 { get; set; }
        public string freeItem9 { get; set; }
        public Nullable<int> RealLevel { get; set; }
        public int isEnd { get; set; }
        public Nullable<decimal> StockRequestOnWayQuantity { get; set; }
        public int id { get; set; }
        public Nullable<int> idbom { get; set; }
        public Nullable<int> idbomchild { get; set; }
        public Nullable<int> idinventory { get; set; }
        public Nullable<int> idsourceinventory { get; set; }
        public Nullable<int> idcustomer { get; set; }
        public Nullable<int> idproject { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<int> idunit2 { get; set; }
        public Nullable<int> sourceVoucherId { get; set; }
        public Nullable<int> sourceVoucherDetailId { get; set; }
        public Nullable<int> parentid { get; set; }
        public Nullable<int> computervoucherid { get; set; }
        public Nullable<int> idPraVoucherDTO { get; set; }
        public Nullable<int> saleOrderId { get; set; }
        public Nullable<int> saleorderdetailid { get; set; }
        public Nullable<int> idsourcevouchertype { get; set; }
        public Nullable<System.DateTime> demandingDate { get; set; }
        public Nullable<System.DateTime> watchtime { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    }
}
