//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_PRA_PraOption
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<byte> isPraInventory { get; set; }
        public Nullable<byte> isPurchaseInventory { get; set; }
        public Nullable<byte> isCarriedForwardOut { get; set; }
        public Nullable<byte> isCarriedForwardIn { get; set; }
        public Nullable<byte> getavailablebeforesomedate { get; set; }
        public Nullable<byte> notquantityonfreeitems { get; set; }
        public Nullable<byte> onquantityonfreeitems { get; set; }
        public Nullable<byte> containsnullwarehouse { get; set; }
        public Nullable<byte> existingquantity { get; set; }
        public Nullable<byte> safequantity { get; set; }
        public Nullable<byte> lowquantity { get; set; }
        public Nullable<byte> purchaseonwayquantity { get; set; }
        public Nullable<byte> purchaseorderonwayquantity { get; set; }
        public Nullable<byte> purchaseorderonwayunaudit { get; set; }
        public Nullable<byte> purchasearrivalquantity { get; set; }
        public Nullable<byte> purchaseforreceivequantity { get; set; }
        public Nullable<byte> onProducingQuantity { get; set; }
        public Nullable<byte> manufacturequantity { get; set; }
        public Nullable<byte> manufacturequantityunaudit { get; set; }
        public Nullable<byte> productforreceivequantity { get; set; }
        public Nullable<byte> transonwayquantity { get; set; }
        public Nullable<byte> otheronwayquantity { get; set; }
        public Nullable<byte> saleonwayquantity { get; set; }
        public Nullable<byte> saleorderquantity { get; set; }
        public Nullable<byte> saleorderquantityunaudit { get; set; }
        public Nullable<byte> saledeliveryquantity { get; set; }
        public Nullable<byte> forsaledispatchquantity { get; set; }
        public Nullable<byte> manufactureMaterialsQuantity { get; set; }
        public Nullable<byte> manufactureforsendquantity { get; set; }
        public Nullable<byte> manufactureforsendunaudit { get; set; }
        public Nullable<byte> materialforsendquantity { get; set; }
        public Nullable<byte> transfordispatchquantity { get; set; }
        public Nullable<byte> otherfordispatchquantity { get; set; }
        public Nullable<byte> purchaserequisitionquantity { get; set; }
        public Nullable<byte> purchaserequisitionunaudit { get; set; }
        public Nullable<int> sequencenumber { get; set; }
        public byte[] ts { get; set; }
        public Nullable<bool> DeliveryOnWayQuantity { get; set; }
        public Nullable<bool> DeliveryOnWayQuantityUnaudit { get; set; }
        public int id { get; set; }
        public Nullable<int> completmentType { get; set; }
        public Nullable<int> completmentTypeForHeigh { get; set; }
        public Nullable<int> GeneratedType { get; set; }
        public Nullable<int> resultmergetype { get; set; }
        public Nullable<int> SourceDocType { get; set; }
        public Nullable<int> suggestiontype { get; set; }
        public Nullable<System.DateTime> availablequantitydate { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    }
}
