//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_ResultTemp
    {
        public Nullable<decimal> suggestionQuantity { get; set; }
        public Nullable<decimal> suggestionQuantity2 { get; set; }
        public Nullable<decimal> grossDemand { get; set; }
        public Nullable<decimal> actualDemand { get; set; }
        public Nullable<decimal> actualDemand2 { get; set; }
        public string freeItem0 { get; set; }
        public string freeItem1 { get; set; }
        public string freeItem2 { get; set; }
        public string freeItem3 { get; set; }
        public string freeItem4 { get; set; }
        public string freeItem5 { get; set; }
        public string freeItem6 { get; set; }
        public string freeItem7 { get; set; }
        public string freeItem8 { get; set; }
        public string freeItem9 { get; set; }
        public string MergeSourceVoucherCode { get; set; }
        public string MergeSaleOrderCode { get; set; }
        public int ID { get; set; }
        public Nullable<int> idBom { get; set; }
        public Nullable<int> idInventory { get; set; }
        public Nullable<int> MergeIdSourceInventory { get; set; }
        public Nullable<int> MergeIdCustomer { get; set; }
        public Nullable<int> MergeSourceVoucherId { get; set; }
        public Nullable<int> sourceVoucherId { get; set; }
        public Nullable<int> sourceVoucherDetailId { get; set; }
        public Nullable<int> idVoucherDTO { get; set; }
        public Nullable<int> MergeSaleOrderId { get; set; }
        public Nullable<int> MergeIdSourcevouchertype { get; set; }
        public Nullable<System.DateTime> demandingDate { get; set; }
        public Nullable<int> MergeIdProject { get; set; }
    }
}
