//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_OutSourceExpenseVoucher_b
    {
        public int id { get; set; }
        public byte[] ts { get; set; }
        public string code { get; set; }
        public string InventoryBarCode { get; set; }
        public Nullable<int> idproject { get; set; }
        public Nullable<int> Idinventory { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string pubuserdefnvc1 { get; set; }
        public Nullable<decimal> pubuserdefdecm1 { get; set; }
        public string pubuserdefnvc2 { get; set; }
        public Nullable<decimal> pubuserdefdecm2 { get; set; }
        public string pubuserdefnvc3 { get; set; }
        public Nullable<decimal> pubuserdefdecm3 { get; set; }
        public string pubuserdefnvc4 { get; set; }
        public Nullable<decimal> pubuserdefdecm4 { get; set; }
        public string freeItem0 { get; set; }
        public string freeItem1 { get; set; }
        public string freeItem2 { get; set; }
        public string freeItem3 { get; set; }
        public string freeItem4 { get; set; }
        public string freeItem5 { get; set; }
        public string freeItem6 { get; set; }
        public string freeItem7 { get; set; }
        public string freeItem8 { get; set; }
        public string freeItem9 { get; set; }
        public Nullable<int> IdWarehouse { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> idunit2 { get; set; }
        public Nullable<decimal> Quantity2 { get; set; }
        public Nullable<decimal> UnitExchangeRate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> OrigPrice { get; set; }
        public Nullable<decimal> DiscountRate { get; set; }
        public Nullable<decimal> OrigDiscountPrice { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> OrigTaxPrice { get; set; }
        public Nullable<decimal> OrigDiscountAmount { get; set; }
        public Nullable<decimal> OrigTax { get; set; }
        public Nullable<decimal> OrigTaxAmount { get; set; }
        public Nullable<decimal> OrigDiscount { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> TaxPrice { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> OrigSettleAmount { get; set; }
        public Nullable<decimal> SettleAmount { get; set; }
        public string Batch { get; set; }
        public string SourceVoucherCode { get; set; }
        public Nullable<int> SourceVoucherId { get; set; }
        public Nullable<System.DateTime> SourceVoucherDate { get; set; }
        public string SaleOrderCode { get; set; }
        public Nullable<int> SaleOrderId { get; set; }
        public Nullable<int> SaleOrderDetailId { get; set; }
        public string OutSourceOrderCode { get; set; }
        public Nullable<int> OutSourceOrderId { get; set; }
        public Nullable<int> outSourceOrderDetailId { get; set; }
        public Nullable<int> IdOutSourceExpenseVoucherDTO { get; set; }
        public Nullable<int> IdsourceVoucherType { get; set; }
        public Nullable<int> SourceVoucherDetailId { get; set; }
        public string SourceVoucherDetailTs { get; set; }
        public string SourceVoucherTs { get; set; }
        public Nullable<int> Idcustomer { get; set; }
        public string Customer { get; set; }
        public string IsNoModify { get; set; }
        public string LastModifiedField { get; set; }
        public Nullable<decimal> BaseQuantity { get; set; }
        public Nullable<int> IdbaseUnit { get; set; }
        public Nullable<decimal> SubQuantity { get; set; }
        public Nullable<int> IdsubUnit { get; set; }
        public Nullable<byte> TaxFlag { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<decimal> BaseDiscountPrice { get; set; }
        public Nullable<decimal> BaseTaxPrice { get; set; }
        public string SourceVoucherBusiTypeCode { get; set; }
    }
}
