//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_OutSourceOrder_b
    {
        public int id { get; set; }
        public string code { get; set; }
        public string inventoryBarCode { get; set; }
        public Nullable<int> idproject { get; set; }
        public Nullable<int> idinventory { get; set; }
        public string freeItem0 { get; set; }
        public string freeItem1 { get; set; }
        public string freeItem2 { get; set; }
        public string freeItem3 { get; set; }
        public string freeItem4 { get; set; }
        public string freeItem5 { get; set; }
        public string freeItem6 { get; set; }
        public string freeItem7 { get; set; }
        public string freeItem8 { get; set; }
        public string freeItem9 { get; set; }
        public Nullable<int> idBom { get; set; }
        public string bomVersion { get; set; }
        public Nullable<int> bomExpandType { get; set; }
        public Nullable<int> idWarehouse { get; set; }
        public string batch { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> unitExchangeRate { get; set; }
        public Nullable<int> idunit2 { get; set; }
        public Nullable<decimal> quantity2 { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> origPrice { get; set; }
        public Nullable<decimal> discountRate { get; set; }
        public Nullable<decimal> origDiscountPrice { get; set; }
        public Nullable<decimal> discountPrice { get; set; }
        public Nullable<decimal> taxRate { get; set; }
        public Nullable<decimal> origTaxPrice { get; set; }
        public Nullable<decimal> taxPrice { get; set; }
        public Nullable<decimal> origDiscountAmount { get; set; }
        public Nullable<decimal> discountAmount { get; set; }
        public Nullable<decimal> origTax { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> origTaxAmount { get; set; }
        public Nullable<decimal> taxAmount { get; set; }
        public Nullable<decimal> origDiscount { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> outSourceSubQuantity { get; set; }
        public Nullable<decimal> outSourceSubPrice { get; set; }
        public Nullable<decimal> origOutSourceSubPrice { get; set; }
        public Nullable<decimal> outSourceSubTaxPrice { get; set; }
        public Nullable<decimal> origOutSourceSubTaxPrice { get; set; }
        public Nullable<int> IdOutSourceSubUnit { get; set; }
        public Nullable<System.DateTime> preStartDate { get; set; }
        public Nullable<System.DateTime> preFinishDate { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
        public Nullable<decimal> wholeSuitMaterialQuantity { get; set; }
        public Nullable<decimal> totalStockInQuantity { get; set; }
        public Nullable<decimal> TotalStockInQuantity2 { get; set; }
        public Nullable<byte> hasPRA { get; set; }
        public string sourceVoucherCode { get; set; }
        public Nullable<int> sourceVoucherId { get; set; }
        public Nullable<int> sourceVoucherDetailId { get; set; }
        public string saleOrderCode { get; set; }
        public Nullable<int> saleOrderId { get; set; }
        public Nullable<int> saleOrderDetailId { get; set; }
        public Nullable<int> idcustomer { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string pubuserdefnvc1 { get; set; }
        public Nullable<decimal> pubuserdefdecm1 { get; set; }
        public string pubuserdefnvc2 { get; set; }
        public Nullable<decimal> pubuserdefdecm2 { get; set; }
        public string pubuserdefnvc3 { get; set; }
        public Nullable<decimal> pubuserdefdecm3 { get; set; }
        public string pubuserdefnvc4 { get; set; }
        public Nullable<decimal> pubuserdefdecm4 { get; set; }
        public Nullable<int> totalpracount { get; set; }
        public Nullable<int> totalStockCount { get; set; }
        public string isNoModify { get; set; }
        public Nullable<decimal> baseQuantity { get; set; }
        public Nullable<int> idbaseunit { get; set; }
        public Nullable<decimal> subQuantity { get; set; }
        public Nullable<int> idsubunit { get; set; }
        public Nullable<int> finishState { get; set; }
        public Nullable<int> processState { get; set; }
        public Nullable<int> sourcecondition { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
        public byte[] ts { get; set; }
        public Nullable<int> idOutSourceOrderDTO { get; set; }
        public Nullable<int> idsourcevouchertype { get; set; }
        public string LastModifiedField { get; set; }
        public Nullable<byte> taxFlag { get; set; }
        public Nullable<byte> IsModifiedPrice { get; set; }
    }
}
