//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_SalesPromotion_Customer
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<int> sequencenumber { get; set; }
        public byte[] ts { get; set; }
        public int id { get; set; }
        public Nullable<int> idDepartment { get; set; }
        public Nullable<int> idDistrict { get; set; }
        public Nullable<int> idCustomer { get; set; }
        public Nullable<int> idCustomerClass { get; set; }
        public Nullable<int> idPerson { get; set; }
        public Nullable<int> idsalesPromotionDTO { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    }
}
