//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_AA_Account
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> IndexOrder { get; set; }
        public Nullable<int> dcdirection { get; set; }
        public Nullable<bool> isEndNode { get; set; }
        public Nullable<int> depth { get; set; }
        public string AccountTypeCode { get; set; }
        public string IndustryTypeCode { get; set; }
        public string CodeParentDTO { get; set; }
        public Nullable<byte> IsCash { get; set; }
        public Nullable<byte> IsBank { get; set; }
        public Nullable<byte> IsCashEquivalents { get; set; }
    }
}
