//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_AA_AssetProp
    {
        public string TradeKind { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<byte> isdepr { get; set; }
        public Nullable<byte> ispreset { get; set; }
        public byte IsSystem { get; set; }
        public int id { get; set; }
        public Nullable<int> provisionway { get; set; }
        public string ExpressionName { get; set; }
    }
}
