//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_AA_AccountType
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> IndexOrder { get; set; }
        public Nullable<int> Trialbalancedirection { get; set; }
        public Nullable<int> Firstnumber { get; set; }
        public Nullable<bool> Trialbalance { get; set; }
        public Nullable<int> Accountclass { get; set; }
        public Nullable<int> DefaultDCDirection { get; set; }
        public string IndustryTypeCode { get; set; }
        public string ClassCode { get; set; }
    }
}
