//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PU_PurchaseArrival_b
    {
        public string code { get; set; }
        public Nullable<byte> taxFlag { get; set; }
        public string compositionQuantity { get; set; }
        public string inventoryLocation { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> origDiscountPrice { get; set; }
        public Nullable<decimal> quantity2 { get; set; }
        public Nullable<decimal> origDiscountPrice2 { get; set; }
        public Nullable<decimal> baseQuantity { get; set; }
        public Nullable<decimal> subQuantity { get; set; }
        public Nullable<decimal> unitExchangeRate { get; set; }
        public Nullable<decimal> origPrice { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> discountRate { get; set; }
        public Nullable<decimal> taxRate { get; set; }
        public Nullable<decimal> origTaxPrice { get; set; }
        public Nullable<decimal> origDiscountAmount { get; set; }
        public Nullable<decimal> origTax { get; set; }
        public Nullable<decimal> origTaxAmount { get; set; }
        public Nullable<decimal> origDiscount { get; set; }
        public Nullable<decimal> discountPrice { get; set; }
        public Nullable<decimal> discountPrice2 { get; set; }
        public Nullable<decimal> taxPrice { get; set; }
        public Nullable<decimal> discountAmount { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> taxAmount { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<byte> isPresent { get; set; }
        public string sourceVoucherCode { get; set; }
        public string saleOrderCode { get; set; }
        public Nullable<decimal> totalInvoiceQuantity { get; set; }
        public Nullable<decimal> totalInvoiceQuantity2 { get; set; }
        public Nullable<decimal> totalInQuantity { get; set; }
        public Nullable<decimal> totalInQuantity2 { get; set; }
        public Nullable<decimal> totalSettleQuantity { get; set; }
        public Nullable<decimal> totalSettleQuantity2 { get; set; }
        public Nullable<decimal> totalReturnQuantity { get; set; }
        public Nullable<decimal> totalReturnQuantity2 { get; set; }
        public Nullable<decimal> totalReduceQuantity { get; set; }
        public Nullable<decimal> totalReduceQuantity2 { get; set; }
        public Nullable<decimal> origSettleAmount { get; set; }
        public Nullable<decimal> settleAmount { get; set; }
        public string batch { get; set; }
        public Nullable<decimal> arrivalQuantity { get; set; }
        public Nullable<decimal> acceptanceQuantity { get; set; }
        public Nullable<decimal> arrivalQuantity2 { get; set; }
        public Nullable<decimal> acceptanceQuantity2 { get; set; }
        public Nullable<decimal> warehouseAdjustAmount { get; set; }
        public string isNoModify { get; set; }
        public Nullable<decimal> basePrice { get; set; }
        public Nullable<decimal> baseDiscountPrice { get; set; }
        public Nullable<decimal> baseTaxPrice { get; set; }
        public Nullable<decimal> totalSettleTaxAmount { get; set; }
        public string receiveVoucherCode { get; set; }
        public string inventoryBarCode { get; set; }
        public string partnerInventoryCode { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public string freeItem0 { get; set; }
        public string freeItem1 { get; set; }
        public string freeItem2 { get; set; }
        public string freeItem3 { get; set; }
        public string freeItem4 { get; set; }
        public string freeItem5 { get; set; }
        public string freeItem6 { get; set; }
        public string freeItem7 { get; set; }
        public string freeItem8 { get; set; }
        public string freeItem9 { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string pubuserdefnvc1 { get; set; }
        public Nullable<decimal> pubuserdefdecm1 { get; set; }
        public string pubuserdefnvc2 { get; set; }
        public Nullable<decimal> pubuserdefdecm2 { get; set; }
        public string pubuserdefnvc3 { get; set; }
        public Nullable<decimal> pubuserdefdecm3 { get; set; }
        public string pubuserdefnvc4 { get; set; }
        public Nullable<decimal> pubuserdefdecm4 { get; set; }
        public Nullable<decimal> totalSettleBaseQuantity { get; set; }
        public Nullable<decimal> totalSettleSubQuantity { get; set; }
        public Nullable<decimal> arrivalBaseQuantity { get; set; }
        public Nullable<decimal> arrivalSubQuantity { get; set; }
        public string purchaseOrderCode { get; set; }
        public string partnerInventoryName { get; set; }
        public Nullable<decimal> shrinkageQuantity { get; set; }
        public Nullable<decimal> shrinkageQuantity2 { get; set; }
        public Nullable<decimal> shrinkageBaseQuantity { get; set; }
        public Nullable<decimal> shrinkageSubQuantity { get; set; }
        public Nullable<decimal> cumInstockShrinkageQuantity { get; set; }
        public Nullable<decimal> cumInstockShrinkageQuantity2 { get; set; }
        public Nullable<decimal> cumInvoiceShrinkageQuantity { get; set; }
        public Nullable<decimal> cumInvoiceShrinkageQuantity2 { get; set; }
        public Nullable<decimal> cumReturnShrinkageQuantity { get; set; }
        public Nullable<decimal> cumReturnShrinkageQuantity2 { get; set; }
        public Nullable<decimal> cumReduceShrinkageQuantity { get; set; }
        public Nullable<decimal> cumReduceShrinkageQuantity2 { get; set; }
        public Nullable<decimal> origShrinkageQuantity { get; set; }
        public Nullable<decimal> origShrinkageQuantity2 { get; set; }
        public Nullable<decimal> cumAccountAmount { get; set; }
        public Nullable<byte> islaborcost { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public int ID { get; set; }
        public Nullable<int> idinventory { get; set; }
        public Nullable<int> idproject { get; set; }
        public Nullable<int> idbaseunit { get; set; }
        public Nullable<int> idsubunit { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<int> idunit2 { get; set; }
        public Nullable<int> idwarehouse { get; set; }
        public Nullable<int> sourceVoucherId { get; set; }
        public Nullable<int> idPurchaseArrivalDTO { get; set; }
        public Nullable<int> sourceVoucherDetailId { get; set; }
        public Nullable<int> purchaseOrderDetailID { get; set; }
        public Nullable<int> saleOrderId { get; set; }
        public Nullable<int> saleOrderDetailId { get; set; }
        public Nullable<int> idsourcevouchertype { get; set; }
        public Nullable<int> receiveVoucherId { get; set; }
        public Nullable<int> receiveVoucherDetailId { get; set; }
        public Nullable<System.DateTime> acceptDate { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
    }
}
