//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RE_ReceiveDetail_b
    {
        public string RetailCode { get; set; }
        public byte[] ts { get; set; }
        public Nullable<long> idReceiveDetailDTO { get; set; }
        public Nullable<long> idRetailDTO { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
        public long ID { get; set; }
    }
}
