//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RE_RetailSettle_PreReceive
    {
        public string code { get; set; }
        public string name { get; set; }
        public string vouchercode { get; set; }
        public Nullable<decimal> origamount { get; set; }
        public Nullable<decimal> orignocancelamount { get; set; }
        public Nullable<decimal> origcancelamount { get; set; }
        public Nullable<decimal> cancelamount { get; set; }
        public Nullable<int> sequencenumber { get; set; }
        public byte[] ts { get; set; }
        public string SourceVoucherCode { get; set; }
        public string SourceVoucherTs { get; set; }
        public int id { get; set; }
        public Nullable<int> iddepartment { get; set; }
        public Nullable<int> idperson { get; set; }
        public Nullable<int> voucherid { get; set; }
        public Nullable<int> SourceVoucherId { get; set; }
        public Nullable<int> idRetailSettleDTO { get; set; }
        public Nullable<int> idVoucherType { get; set; }
        public Nullable<System.DateTime> voucherdate { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    }
}
