//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RE_Retail
    {
        public string code { get; set; }
        public string name { get; set; }
        public string docno { get; set; }
        public string docclass { get; set; }
        public Nullable<int> accountingperiod { get; set; }
        public string docid { get; set; }
        public Nullable<int> accountingyear { get; set; }
        public string memo { get; set; }
        public string maker { get; set; }
        public string auditor { get; set; }
        public string reviser { get; set; }
        public Nullable<byte> iscarriedforwardout { get; set; }
        public Nullable<byte> iscarriedforwardin { get; set; }
        public Nullable<byte> ismodifiedcode { get; set; }
        public Nullable<int> sequencenumber { get; set; }
        public string customername { get; set; }
        public string customeraddress { get; set; }
        public string customerlinkman { get; set; }
        public string customerphone { get; set; }
        public string customerrequest { get; set; }
        public string shiftcode { get; set; }
        public string auditedtime { get; set; }
        public string poscode { get; set; }
        public string posname { get; set; }
        public int isdealed { get; set; }
        public Nullable<decimal> totalretailamount { get; set; }
        public Nullable<decimal> totaltaxamount { get; set; }
        public Nullable<decimal> discountsandallowances { get; set; }
        public Nullable<decimal> totaldiscountamount { get; set; }
        public Nullable<decimal> wipechange { get; set; }
        public Nullable<decimal> integral { get; set; }
        public Nullable<int> iscleared { get; set; }
        public string usercode { get; set; }
        public string username { get; set; }
        public byte[] ts { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string priuserdefnvc5 { get; set; }
        public Nullable<decimal> priuserdefdecm5 { get; set; }
        public string priuserdefnvc6 { get; set; }
        public Nullable<decimal> priuserdefdecm6 { get; set; }
        public string pubuserdefnvc1 { get; set; }
        public Nullable<decimal> pubuserdefdecm1 { get; set; }
        public string pubuserdefnvc2 { get; set; }
        public Nullable<decimal> pubuserdefdecm2 { get; set; }
        public string pubuserdefnvc3 { get; set; }
        public Nullable<decimal> pubuserdefdecm3 { get; set; }
        public string pubuserdefnvc4 { get; set; }
        public Nullable<decimal> pubuserdefdecm4 { get; set; }
        public string pubuserdefnvc5 { get; set; }
        public Nullable<decimal> pubuserdefdecm5 { get; set; }
        public string pubuserdefnvc6 { get; set; }
        public Nullable<decimal> pubuserdefdecm6 { get; set; }
        public Nullable<decimal> SteadCashIntegral { get; set; }
        public Nullable<decimal> balancestorage { get; set; }
        public string dailycode { get; set; }
        public Nullable<decimal> storagesettleamount { get; set; }
        public Nullable<decimal> integralsteadcashamount { get; set; }
        public Nullable<decimal> givechangeforstorageamount { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public Nullable<decimal> balanceintegral { get; set; }
        public string RetailSettleCode { get; set; }
        public string ExternalCode { get; set; }
        public int id { get; set; }
        public Nullable<int> idbusitype { get; set; }
        public Nullable<int> idmember { get; set; }
        public Nullable<int> idstore { get; set; }
        public Nullable<int> idmarketingorgan { get; set; }
        public Nullable<int> idperson { get; set; }
        public Nullable<int> idRetailSettle { get; set; }
        public Nullable<int> idDepartment_Store { get; set; }
        public Nullable<int> idDistrict_Member { get; set; }
        public Nullable<int> idMembertype { get; set; }
        public Nullable<int> iscancel { get; set; }
        public Nullable<int> issaleout { get; set; }
        public Nullable<int> shift { get; set; }
        public Nullable<int> voucherstate { get; set; }
        public Nullable<int> auditorid { get; set; }
        public Nullable<int> makerid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<long> iddailyvoucher { get; set; }
        public Nullable<long> idshiftvoucher { get; set; }
        public Nullable<System.DateTime> madedate { get; set; }
        public Nullable<System.DateTime> auditeddate { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
        public Nullable<System.DateTime> receivingmaturity { get; set; }
        public Nullable<System.DateTime> voucherdate { get; set; }
        public Nullable<long> RetailID { get; set; }
        public string payordercode { get; set; }
    }
}
