//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SA_SaleExpenseAllocationDetail
    {
        public string code { get; set; }
        public Nullable<decimal> amount { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public string freeItem0 { get; set; }
        public string freeItem1 { get; set; }
        public string freeItem2 { get; set; }
        public string freeItem3 { get; set; }
        public string freeItem4 { get; set; }
        public string freeItem5 { get; set; }
        public string freeItem6 { get; set; }
        public string freeItem7 { get; set; }
        public string freeItem8 { get; set; }
        public string freeItem9 { get; set; }
        public string SourceVoucherCode { get; set; }
        public string SourceVoucherMemo { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<byte> ispresent { get; set; }
        public int id { get; set; }
        public Nullable<int> iddepartment { get; set; }
        public Nullable<int> idinventory { get; set; }
        public Nullable<int> idpartner { get; set; }
        public Nullable<int> idsettlecustomer { get; set; }
        public Nullable<int> idperson { get; set; }
        public Nullable<int> idproject { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<int> SourceVoucherId { get; set; }
        public Nullable<int> SourceVoucherDetailId { get; set; }
        public Nullable<int> idsaledelivery { get; set; }
        public Nullable<int> idsaledeliverydetail { get; set; }
        public Nullable<int> idSaleExpenseAllocationDTO { get; set; }
        public Nullable<int> idsaleinvoice { get; set; }
        public Nullable<int> idsaleinvoicedetail { get; set; }
        public Nullable<int> idsourcevouchertype { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<System.DateTime> SourceVoucherDate { get; set; }
    }
}
