//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_FC_MergeOption
    {
        public Nullable<int> SequenceNumber { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<byte> IsEnabled { get; set; }
        public Nullable<byte> IsVisible { get; set; }
        public byte[] Ts { get; set; }
        public int ID { get; set; }
        public string ExpressionName { get; set; }
    }
}
