//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_FC_AccountExtendRule
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<int> rowidx { get; set; }
        public Nullable<decimal> inventorypriuserdefdecm0 { get; set; }
        public string inventorypriuserdefnvc0 { get; set; }
        public Nullable<decimal> inventorypriuserdefdecm1 { get; set; }
        public string inventorypriuserdefnvc1 { get; set; }
        public Nullable<decimal> inventorypriuserdefdecm2 { get; set; }
        public string inventorypriuserdefnvc2 { get; set; }
        public Nullable<decimal> inventorypriuserdefdecm3 { get; set; }
        public string inventorypriuserdefnvc3 { get; set; }
        public Nullable<decimal> inventorypriuserdefdecm4 { get; set; }
        public string inventorypriuserdefnvc4 { get; set; }
        public Nullable<decimal> headerpubuserdefdecm0 { get; set; }
        public string headerpubuserdefnvc0 { get; set; }
        public Nullable<decimal> headerpubuserdefdecm1 { get; set; }
        public string headerpubuserdefnvc1 { get; set; }
        public Nullable<decimal> headerpubuserdefdecm2 { get; set; }
        public string headerpubuserdefnvc2 { get; set; }
        public Nullable<decimal> headerpubuserdefdecm3 { get; set; }
        public string headerpubuserdefnvc3 { get; set; }
        public Nullable<decimal> headerpubuserdefdecm4 { get; set; }
        public string headerpubuserdefnvc4 { get; set; }
        public Nullable<decimal> headerpubuserdefdecm5 { get; set; }
        public string headerpubuserdefnvc5 { get; set; }
        public Nullable<decimal> headerpriuserdefdecm0 { get; set; }
        public string headerpriuserdefnvc0 { get; set; }
        public Nullable<decimal> headerpriuserdefdecm1 { get; set; }
        public string headerpriuserdefnvc1 { get; set; }
        public Nullable<decimal> headerpriuserdefdecm2 { get; set; }
        public string headerpriuserdefnvc2 { get; set; }
        public Nullable<decimal> headerpriuserdefdecm3 { get; set; }
        public string headerpriuserdefnvc3 { get; set; }
        public Nullable<decimal> headerpriuserdefdecm4 { get; set; }
        public string headerpriuserdefnvc4 { get; set; }
        public Nullable<decimal> headerpriuserdefdecm5 { get; set; }
        public string headerpriuserdefnvc5 { get; set; }
        public Nullable<decimal> detailspubuserdefdecm0 { get; set; }
        public string detailspubuserdefnvc0 { get; set; }
        public Nullable<decimal> detailspubuserdefdecm1 { get; set; }
        public string detailspubuserdefnvc1 { get; set; }
        public Nullable<decimal> detailspubuserdefdecm2 { get; set; }
        public string detailspubuserdefnvc2 { get; set; }
        public Nullable<decimal> detailspubuserdefdecm3 { get; set; }
        public string detailspubuserdefnvc3 { get; set; }
        public Nullable<decimal> detailspriuserdefdecm0 { get; set; }
        public string detailspriuserdefnvc0 { get; set; }
        public Nullable<decimal> detailspriuserdefdecm1 { get; set; }
        public string detailspriuserdefnvc1 { get; set; }
        public Nullable<decimal> detailspriuserdefdecm2 { get; set; }
        public string detailspriuserdefnvc2 { get; set; }
        public Nullable<decimal> detailspriuserdefdecm3 { get; set; }
        public string detailspriuserdefnvc3 { get; set; }
        public string accountcode { get; set; }
        public string accountname { get; set; }
        public Nullable<int> sequencenumber { get; set; }
        public byte[] ts { get; set; }
        public Nullable<byte> islaborcost { get; set; }
        public string summary { get; set; }
        public int id { get; set; }
        public Nullable<int> idaccount { get; set; }
        public Nullable<int> idassetClass { get; set; }
        public Nullable<int> idassetProp { get; set; }
        public Nullable<int> idbankaccount { get; set; }
        public Nullable<int> idbusitype { get; set; }
        public Nullable<int> idcurrency { get; set; }
        public Nullable<int> iddepartment { get; set; }
        public Nullable<int> iddistrict { get; set; }
        public Nullable<int> idexpenseitem { get; set; }
        public Nullable<int> idhandleReason { get; set; }
        public Nullable<int> idincDecWay { get; set; }
        public Nullable<int> idincome { get; set; }
        public Nullable<int> idinventory { get; set; }
        public Nullable<int> idinventoryclass { get; set; }
        public Nullable<int> idpartner { get; set; }
        public Nullable<int> idpartnerclass { get; set; }
        public Nullable<int> idproject { get; set; }
        public Nullable<int> idprojectClass { get; set; }
        public Nullable<int> idrdstyle { get; set; }
        public Nullable<int> idwarehouse { get; set; }
        public Nullable<int> adjusttype { get; set; }
        public Nullable<int> checkstate { get; set; }
        public Nullable<int> expensetype { get; set; }
        public Nullable<int> incomeExpensesType { get; set; }
        public Nullable<int> ProfitLossType { get; set; }
        public Nullable<int> idAccountRuleDTO { get; set; }
        public Nullable<int> idvouchertype { get; set; }
        public string ExpressionName { get; set; }
        public Nullable<int> IdSettleStyle { get; set; }
        public Nullable<int> isreplaced { get; set; }
        public Nullable<byte> IsPresent { get; set; }
    }
}
