//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_optexpression
    {
        public string ExpressionName { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string ExpressionValue { get; set; }
        public int id { get; set; }
        public string ExpressionType { get; set; }
        public string ExpressionWhere { get; set; }
        public string ExceptionStatus { get; set; }
    }
}
