//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_TransferredCode
    {
        public string basearchivecode { get; set; }
        public string basearchivename { get; set; }
        public string transferredcode { get; set; }
        public byte[] ts { get; set; }
        public int id { get; set; }
        public byte IsSystem { get; set; }
        public int basearchiveid { get; set; }
        public int idcodingprefixion { get; set; }
        public string ExpressionName { get; set; }
    }
}
