//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_UsedRule
    {
        public string prefixion1 { get; set; }
        public string prefixion2 { get; set; }
        public string prefixion3 { get; set; }
        public string separator { get; set; }
        public int codelen { get; set; }
        public int serialnolength { get; set; }
        public string allprefixion { get; set; }
        public byte[] ts { get; set; }
        public string startcode { get; set; }
        public string endcode { get; set; }
        public int id { get; set; }
        public Nullable<int> idvouchertype { get; set; }
    }
}
