//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_AdjustCostVoucher_b
    {
        public string code { get; set; }
        public string sourceVoucherCode { get; set; }
        public string processCode { get; set; }
        public string batch { get; set; }
        public Nullable<decimal> amount { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public string freeItem0 { get; set; }
        public string freeItem1 { get; set; }
        public string freeItem2 { get; set; }
        public string freeItem3 { get; set; }
        public string freeItem4 { get; set; }
        public string freeItem5 { get; set; }
        public string freeItem6 { get; set; }
        public string freeItem7 { get; set; }
        public string freeItem8 { get; set; }
        public string freeItem9 { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string pubuserdefnvc1 { get; set; }
        public Nullable<decimal> pubuserdefdecm1 { get; set; }
        public string pubuserdefnvc2 { get; set; }
        public Nullable<decimal> pubuserdefdecm2 { get; set; }
        public string pubuserdefnvc3 { get; set; }
        public Nullable<decimal> pubuserdefdecm3 { get; set; }
        public string pubuserdefnvc4 { get; set; }
        public string InvBarCode { get; set; }
        public Nullable<decimal> pubuserdefdecm4 { get; set; }
        public int id { get; set; }
        public Nullable<int> idinventory { get; set; }
        public Nullable<int> idproduct { get; set; }
        public Nullable<int> idproject { get; set; }
        public Nullable<int> idBaseUnit { get; set; }
        public Nullable<int> idSubUnit { get; set; }
        public Nullable<int> idwarehouse { get; set; }
        public Nullable<int> adjustFlag { get; set; }
        public Nullable<int> idsourcevouchertype { get; set; }
        public Nullable<int> idAdjustCostVoucherDTO { get; set; }
        public Nullable<int> fromVoucherID { get; set; }
        public Nullable<int> fromVoucherDetailID { get; set; }
        public Nullable<int> sourceVoucherID { get; set; }
        public Nullable<int> rdvoucherDetailID { get; set; }
        public Nullable<int> sourceVoucherDetailID { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<int> idFromVoucherType { get; set; }
    }
}
