//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_AssistantDataRelation
    {
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<byte> isManual { get; set; }
        public Nullable<byte> iscarriedforwardout { get; set; }
        public Nullable<byte> iscarriedforwardin { get; set; }
        public Nullable<int> accountYear { get; set; }
        public Nullable<int> accountPeriod { get; set; }
        public Nullable<decimal> outAmount { get; set; }
        public Nullable<decimal> outPrice { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public Nullable<decimal> adjustAmount { get; set; }
        public Nullable<byte> isInStock { get; set; }
        public Nullable<byte> IsRedVoucher { get; set; }
        public Nullable<decimal> outVoucherAmount { get; set; }
        public string AccountYearPeriod { get; set; }
        public int id { get; set; }
        public Nullable<int> idvouchertype { get; set; }
        public Nullable<int> assistantDataBookID { get; set; }
        public Nullable<int> voucherID { get; set; }
        public Nullable<int> voucherDetailID { get; set; }
        public Nullable<int> subsidiaryBookID { get; set; }
        public Nullable<System.DateTime> accountDate { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<decimal> subsidiaryAmount { get; set; }
    }
}
