//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_CheckVoucherSelectSetting
    {
        public int voucherid { get; set; }
        public string FieldName { get; set; }
        public string BeginValue { get; set; }
        public string EndValue { get; set; }
        public string BeginText { get; set; }
        public string EndText { get; set; }
        public byte[] Ts { get; set; }
    }
}
