//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_PositionInitDetail
    {
        public string code { get; set; }
        public string batch { get; set; }
        public Nullable<decimal> subQuantity { get; set; }
        public Nullable<decimal> baseQuantity { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> quantity2 { get; set; }
        public string inventoryLocation { get; set; }
        public Nullable<decimal> changeRate { get; set; }
        public byte[] ts { get; set; }
        public string freeItem0 { get; set; }
        public string freeItem1 { get; set; }
        public string freeItem2 { get; set; }
        public string freeItem3 { get; set; }
        public string freeItem4 { get; set; }
        public string freeItem5 { get; set; }
        public string freeItem6 { get; set; }
        public string freeItem7 { get; set; }
        public string freeItem8 { get; set; }
        public string freeItem9 { get; set; }
        public Nullable<byte> iscarriedforwardout { get; set; }
        public Nullable<byte> iscarriedforwardin { get; set; }
        public int id { get; set; }
        public Nullable<int> idinventory { get; set; }
        public Nullable<int> idbaseunit { get; set; }
        public Nullable<int> idsubunit { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<int> idunit2 { get; set; }
        public Nullable<int> idwarehouse { get; set; }
        public Nullable<int> voucherState { get; set; }
        public Nullable<int> idPositionInitDTO { get; set; }
        public Nullable<int> recieveVoucherID { get; set; }
        public Nullable<System.DateTime> addendumDate { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
        public Nullable<System.DateTime> voucherDate { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
    }
}
