//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_RDRecord
    {
        public string code { get; set; }
        public string dispatchAddress { get; set; }
        public string contact { get; set; }
        public string contactPhone { get; set; }
        public string sourceVoucherCode { get; set; }
        public string saleOrderCode { get; set; }
        public string purchaseArrivalCode { get; set; }
        public string productReceiveCode { get; set; }
        public string saleDeliveryCode { get; set; }
        public Nullable<int> printTime { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<byte> rdDirectionFlag { get; set; }
        public Nullable<byte> isCostAccount { get; set; }
        public Nullable<byte> isMergedFlow { get; set; }
        public Nullable<byte> isAutoGenerate { get; set; }
        public string memo { get; set; }
        public string isNoModify { get; set; }
        public string maker { get; set; }
        public string auditor { get; set; }
        public string reviser { get; set; }
        public Nullable<byte> iscarriedforwardout { get; set; }
        public Nullable<byte> iscarriedforwardin { get; set; }
        public Nullable<byte> ismodifiedcode { get; set; }
        public Nullable<int> accountingperiod { get; set; }
        public string docid { get; set; }
        public Nullable<int> accountingyear { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string priuserdefnvc5 { get; set; }
        public Nullable<decimal> priuserdefdecm5 { get; set; }
        public string priuserdefnvc6 { get; set; }
        public Nullable<decimal> priuserdefdecm6 { get; set; }
        public string pubuserdefnvc1 { get; set; }
        public Nullable<decimal> pubuserdefdecm1 { get; set; }
        public string pubuserdefnvc2 { get; set; }
        public Nullable<decimal> pubuserdefdecm2 { get; set; }
        public string pubuserdefnvc3 { get; set; }
        public Nullable<decimal> pubuserdefdecm3 { get; set; }
        public string pubuserdefnvc4 { get; set; }
        public Nullable<decimal> pubuserdefdecm4 { get; set; }
        public string pubuserdefnvc5 { get; set; }
        public Nullable<decimal> pubuserdefdecm5 { get; set; }
        public string pubuserdefnvc6 { get; set; }
        public Nullable<decimal> pubuserdefdecm6 { get; set; }
        public Nullable<int> VoucherYear { get; set; }
        public Nullable<int> VoucherPeriod { get; set; }
        public Nullable<System.DateTime> SourceVoucherDate { get; set; }
        public Nullable<decimal> exchangeRate { get; set; }
        public string ManufactureOrderCode { get; set; }
        public string DelegateDispatchCode { get; set; }
        public string BeforeUpgrade { get; set; }
        public Nullable<decimal> TotalOrigTaxAmount { get; set; }
        public Nullable<decimal> TotalTaxAmount { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public string Mobilephone { get; set; }
        public string Address { get; set; }
        public string ExternalCode { get; set; }
        public int id { get; set; }
        public Nullable<int> idbusitype { get; set; }
        public Nullable<int> idcurrency { get; set; }
        public Nullable<int> iddepartment { get; set; }
        public Nullable<int> iddistrict { get; set; }
        public Nullable<int> idmember { get; set; }
        public Nullable<int> IdStore { get; set; }
        public Nullable<int> IdMarketingOrgan { get; set; }
        public Nullable<int> idpartner { get; set; }
        public Nullable<int> idsettleCustomer { get; set; }
        public Nullable<int> idclerk { get; set; }
        public Nullable<int> idqualityinspector { get; set; }
        public Nullable<int> idproject { get; set; }
        public Nullable<int> idrdstyle { get; set; }
        public Nullable<int> idinwarehouse { get; set; }
        public Nullable<int> idwarehouse { get; set; }
        public Nullable<int> idCollaborateUpVoucherType { get; set; }
        public Nullable<int> idCollaborateUpVoucher { get; set; }
        public Nullable<int> accountState { get; set; }
        public Nullable<int> deliveryState { get; set; }
        public Nullable<int> settleStatus { get; set; }
        public Nullable<int> transportType { get; set; }
        public Nullable<int> voucherState { get; set; }
        public Nullable<int> auditorid { get; set; }
        public Nullable<int> makerid { get; set; }
        public Nullable<int> sourceVoucherId { get; set; }
        public Nullable<int> purchaseArrivalId { get; set; }
        public Nullable<int> saleDeliveryId { get; set; }
        public Nullable<int> saleOrderId { get; set; }
        public Nullable<int> idsourcevouchertype { get; set; }
        public Nullable<int> idvouchertype { get; set; }
        public Nullable<int> productReceiveId { get; set; }
        public Nullable<System.DateTime> maturityDate { get; set; }
        public Nullable<System.DateTime> voucherdate { get; set; }
        public Nullable<System.DateTime> madedate { get; set; }
        public Nullable<System.DateTime> auditeddate { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<int> DataSource { get; set; }
        public Nullable<byte> IsCostAccounted { get; set; }
    }
}
