//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_SubTemp
    {
        public string Batch { get; set; }
        public Nullable<int> orderno { get; set; }
        public Nullable<int> AccountYear { get; set; }
        public Nullable<int> AccountPeriod { get; set; }
        public string AccountYearPeriod { get; set; }
        public int Idinventory { get; set; }
        public Nullable<int> Idwarehouse { get; set; }
        public Nullable<int> valuetype { get; set; }
        public Nullable<int> fromVoucherID { get; set; }
        public Nullable<int> fromVoucherDetailID { get; set; }
        public Nullable<System.DateTime> AccountDate { get; set; }
        public Nullable<int> fromVoucherTypeID { get; set; }
    }
}
