//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_safestocksetting
    {
        public string code { get; set; }
        public Nullable<decimal> safeQuantity { get; set; }
        public Nullable<decimal> topQuantity { get; set; }
        public Nullable<decimal> lowQuantity { get; set; }
        public Nullable<int> replenishmentLeadTime { get; set; }
        public Nullable<int> replenishmentSalesDays { get; set; }
        public string updatedBy { get; set; }
        public byte[] ts { get; set; }
        public int id { get; set; }
        public Nullable<int> idinventory { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<int> idwarehouse { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
