//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_TranVoucherRecord
    {
        public Nullable<int> OrderNo { get; set; }
        public Nullable<bool> Flag { get; set; }
        public Nullable<decimal> INQuantity { get; set; }
        public Nullable<decimal> InVoucherPrice { get; set; }
        public Nullable<decimal> InVoucherAmount { get; set; }
        public Nullable<decimal> OutQuantity { get; set; }
        public Nullable<decimal> OutQuantity2 { get; set; }
        public int Id { get; set; }
        public Nullable<int> AssistantBookId { get; set; }
        public Nullable<int> RelationDataId { get; set; }
    }
}
