//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_TransVoucher_b
    {
        public string code { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> quantity2 { get; set; }
        public Nullable<decimal> baseQuantity { get; set; }
        public Nullable<decimal> subQuantity { get; set; }
        public Nullable<decimal> outPrice { get; set; }
        public Nullable<decimal> outAmount { get; set; }
        public Nullable<decimal> inPrice { get; set; }
        public Nullable<decimal> inAmount { get; set; }
        public Nullable<decimal> balanceAmount { get; set; }
        public Nullable<decimal> changeRate { get; set; }
        public Nullable<byte> isManualCost { get; set; }
        public string batch { get; set; }
        public string receiveVoucherCode { get; set; }
        public byte[] ts { get; set; }
        public string updatedBy { get; set; }
        public string freeItem0 { get; set; }
        public string freeItem1 { get; set; }
        public string freeItem2 { get; set; }
        public string freeItem3 { get; set; }
        public string freeItem4 { get; set; }
        public string freeItem5 { get; set; }
        public string freeItem6 { get; set; }
        public string freeItem7 { get; set; }
        public string freeItem8 { get; set; }
        public string freeItem9 { get; set; }
        public string priuserdefnvc1 { get; set; }
        public Nullable<decimal> priuserdefdecm1 { get; set; }
        public string priuserdefnvc2 { get; set; }
        public Nullable<decimal> priuserdefdecm2 { get; set; }
        public string priuserdefnvc3 { get; set; }
        public Nullable<decimal> priuserdefdecm3 { get; set; }
        public string priuserdefnvc4 { get; set; }
        public Nullable<decimal> priuserdefdecm4 { get; set; }
        public string pubuserdefnvc1 { get; set; }
        public Nullable<decimal> pubuserdefdecm1 { get; set; }
        public string pubuserdefnvc2 { get; set; }
        public Nullable<decimal> pubuserdefdecm2 { get; set; }
        public string pubuserdefnvc3 { get; set; }
        public Nullable<decimal> pubuserdefdecm3 { get; set; }
        public string pubuserdefnvc4 { get; set; }
        public string InvBarCode { get; set; }
        public Nullable<decimal> pubuserdefdecm4 { get; set; }
        public string compositionQuantity { get; set; }
        public Nullable<decimal> inPrice2 { get; set; }
        public Nullable<decimal> outPrice2 { get; set; }
        public string SaleOrderCode { get; set; }
        public string SourceVoucherCode { get; set; }
        public string isNoModify { get; set; }
        public string BoxNumber { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public int id { get; set; }
        public Nullable<int> idinventory { get; set; }
        public Nullable<int> idinofinvlocation { get; set; }
        public Nullable<int> idoutofinvlocation { get; set; }
        public Nullable<int> idproject { get; set; }
        public Nullable<int> idbaseunit { get; set; }
        public Nullable<int> idsubunit { get; set; }
        public Nullable<int> idunit { get; set; }
        public Nullable<int> idunit2 { get; set; }
        public Nullable<int> SourceVoucherId { get; set; }
        public Nullable<int> SourceVoucherDetailId { get; set; }
        public Nullable<int> SaleOrderId { get; set; }
        public Nullable<int> SaleOrderDetailId { get; set; }
        public Nullable<int> idsourcevouchertype { get; set; }
        public Nullable<int> receiveVoucherId { get; set; }
        public Nullable<int> receiveVoucherDetailId { get; set; }
        public Nullable<int> idTransVoucherDTO { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
    }
}
