//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_0_EAP_Rpt_ST_PurchaseReceiveDetailRpt_5e5dce63_f51a_7633_f861_7af2303d9d11608_Index
    {
        public int tmpIndex { get; set; }
        public Nullable<int> rowIndex { get; set; }
    }
}
