//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_0_EAP_Rpt_GL_AuxBalanceSumRpt_db758e5d_1d24_976e_e267_8275ce0bd1f41078_Index
    {
        public int tmpIndex { get; set; }
        public Nullable<int> rowIndex { get; set; }
    }
}
