//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_0_EAP_Rpt_ST_MaterialDispatchDetailRpt_5d26542f_df3a_d35b_63b0_123e6fcb20c81132_Index
    {
        public int tmpIndex { get; set; }
        public Nullable<int> rowIndex { get; set; }
    }
}
