//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_0_EAP_Rpt_SA_SaleDeliveryDetailRpt_d1275148_8ffe_928e_ac72_50bd38ab39af864
    {
        public Nullable<int> rowIndex { get; set; }
        public Nullable<System.DateTime> voucherdate { get; set; }
        public string busiTypeName { get; set; }
        public Nullable<int> partnerClassID { get; set; }
        public int partnerID { get; set; }
        public string partnerCode { get; set; }
        public string partnerName { get; set; }
        public string SaleDelivery_Customerpriuserdefnvc1 { get; set; }
        public string SaleDelivery_Customerpriuserdefnvc2 { get; set; }
        public string SaleDelivery_Customerpriuserdefnvc3 { get; set; }
        public Nullable<int> districtID { get; set; }
        public Nullable<int> departmentID { get; set; }
        public string departmentName { get; set; }
        public Nullable<int> personID { get; set; }
        public string personCode { get; set; }
        public string personName { get; set; }
        public Nullable<int> projectClassID { get; set; }
        public Nullable<int> IDProject { get; set; }
        public Nullable<int> IDSettleCustomerClass { get; set; }
        public Nullable<int> IDSettleCustomer { get; set; }
        public string SettleCustomer { get; set; }
        public int voucherID { get; set; }
        public Nullable<System.DateTime> recivingMaturity { get; set; }
        public Nullable<int> currencyID { get; set; }
        public string reciveTypeName { get; set; }
        public Nullable<byte> isCounteractDelivery { get; set; }
        public Nullable<decimal> origSettleAmount { get; set; }
        public Nullable<decimal> origAllowances { get; set; }
        public string voucherState { get; set; }
        public string saleOutName { get; set; }
        public string cancelState { get; set; }
        public Nullable<int> DataSourceID { get; set; }
        public Nullable<int> inventoryClassID { get; set; }
        public int inventoryID { get; set; }
        public string inventoryName { get; set; }
        public string specification { get; set; }
        public string Brand { get; set; }
        public Nullable<int> warehouseID { get; set; }
        public string unit1Name { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> origDiscountPrice { get; set; }
        public Nullable<decimal> taxRate { get; set; }
        public Nullable<decimal> origTaxPrice { get; set; }
        public Nullable<decimal> origDiscountAmount { get; set; }
        public Nullable<decimal> origTax { get; set; }
        public Nullable<decimal> origTaxAmount { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public Nullable<decimal> SaleDeliveryDetailDTOpriuserdefdecm1 { get; set; }
        public Nullable<decimal> SaleDeliveryDetailDTOpriuserdefdecm2 { get; set; }
        public Nullable<decimal> saleOutQuantity { get; set; }
        public Nullable<decimal> invoiceQuantity { get; set; }
        public Nullable<decimal> returnQuantity { get; set; }
        public Nullable<decimal> counteractQuantity { get; set; }
        public Nullable<decimal> SDDetailorigSettleAmount { get; set; }
        public string saleOrderCode { get; set; }
        public int detailID { get; set; }
        public string DetailMemo { get; set; }
        public string SaleDeliveryDetailDTOCode { get; set; }
        public string FirstDetailCode { get; set; }
    }
}
