//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_0_EAP_Rpt_ST_MaterialDispatchSumRpt_eb8f12a9_26c8_26a4_8ec6_dfcec103897f774_Grp
    {
        public int grpid { get; set; }
        public Nullable<int> maxId { get; set; }
        public Nullable<int> minId { get; set; }
        public Nullable<int> IDInventoryClass_lev1 { get; set; }
        public Nullable<int> IDInventoryClass_lev2 { get; set; }
        public Nullable<int> IDInventoryClass_lev3 { get; set; }
        public Nullable<int> IDInventoryClass_lev4 { get; set; }
        public Nullable<int> IDInventoryClass_lev5 { get; set; }
        public Nullable<int> IDDepartment_lev1 { get; set; }
        public Nullable<int> IDDepartment_lev2 { get; set; }
        public int levelGrp { get; set; }
    }
}
