//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_0_EAP_Rpt_ST_PurchaseReceiveDetailRpt_5d7fa07b_de91_8a8e_0441_d6f0f614b625608
    {
        public Nullable<int> rowIndex { get; set; }
        public string VoucherCode { get; set; }
        public string VoucherTypeCode { get; set; }
        public int PurchaseReceiveID { get; set; }
        public string VoucherType { get; set; }
        public Nullable<int> IDInventoryClass_lev1 { get; set; }
        public Nullable<int> IDInventoryClass_lev2 { get; set; }
        public Nullable<int> IDInventoryClass_lev3 { get; set; }
        public Nullable<int> IDInventoryClass_lev4 { get; set; }
        public Nullable<int> IDInventoryClass_lev5 { get; set; }
        public string InventoryClass_lev1 { get; set; }
        public string InventoryClass_lev2 { get; set; }
        public string InventoryClass_lev3 { get; set; }
        public string InventoryClass_lev4 { get; set; }
        public string InventoryClass_lev5 { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<int> IDBusinessType { get; set; }
        public string BusinessType { get; set; }
        public int IDWarehouse { get; set; }
        public string WarehouseCode { get; set; }
        public string Warehouse { get; set; }
        public Nullable<int> projectClassID { get; set; }
        public Nullable<int> IDProject { get; set; }
        public Nullable<int> IDReceiveStyle { get; set; }
        public string ReceiveStyle { get; set; }
        public Nullable<int> IDCurrency { get; set; }
        public Nullable<int> IDVendorClass { get; set; }
        public Nullable<int> IDVendor { get; set; }
        public string VendorCode { get; set; }
        public string Vendor { get; set; }
        public Nullable<int> IDDepartment { get; set; }
        public string DepartmentCode { get; set; }
        public string Department { get; set; }
        public Nullable<int> IDClerk { get; set; }
        public string ClerkCode { get; set; }
        public string Clerk { get; set; }
        public string Memo { get; set; }
        public string Maker { get; set; }
        public string Auditor { get; set; }
        public int IDInventory { get; set; }
        public string InventoryCode { get; set; }
        public string Inventory { get; set; }
        public string Specification { get; set; }
        public string Brand { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> origPrice { get; set; }
        public Nullable<decimal> origAmount { get; set; }
        public Nullable<decimal> origTax { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> ReceiveAdjust { get; set; }
        public Nullable<decimal> Feeadjust { get; set; }
        public Nullable<decimal> Totalamount { get; set; }
        public Nullable<decimal> Feeamount { get; set; }
        public Nullable<int> IDSourceVoucherType { get; set; }
    }
}
