//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_1_SM_FC_PBSAMCheckAccount
    {
        public byte[] ts { get; set; }
        public string ValueType { get; set; }
        public Nullable<decimal> AssetOrigAmount { get; set; }
        public Nullable<decimal> GLOrigAmount { get; set; }
        public Nullable<decimal> OrigAmountDiff { get; set; }
        public int id { get; set; }
        public Nullable<int> idAccount { get; set; }
        public Nullable<int> idAssetProp { get; set; }
    }
}
