//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_0_EAP_Rpt_SA_SaleOrderDetailRpt_8469f6ef_0423_4fdf_b6f6_3a908a0e65d5742_Index
    {
        public int tmpIndex { get; set; }
        public Nullable<int> rowIndex { get; set; }
    }
}
