//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_0_EAP_Rpt_ST_RDSInventoryDetailRpt_d5e85cc8_9935_4eb9_e992_52c62bb93ce61085
    {
        public int rowIndex { get; set; }
        public int eap_reportrowtype { get; set; }
        public Nullable<decimal> rateofexchange { get; set; }
        public int UnitChangeType { get; set; }
        public Nullable<int> IDInventory { get; set; }
        public Nullable<int> IDWarehouse { get; set; }
        public string WarehouseCode { get; set; }
        public string Warehouse { get; set; }
        public string InventoryCode { get; set; }
        public string Inventory { get; set; }
        public string Specification { get; set; }
        public string BaseUnit { get; set; }
        public string Period { get; set; }
        public Nullable<int> projectClassID { get; set; }
        public Nullable<int> IDProject { get; set; }
        public Nullable<int> IDInventoryClass { get; set; }
        public string InventoryClass { get; set; }
        public string VoucherType { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string VoucherCode { get; set; }
        public string VoucherTypeCode { get; set; }
        public Nullable<int> IDRDRecord { get; set; }
        public string BusinessType { get; set; }
        public string docno { get; set; }
        public string DOCID { get; set; }
        public Nullable<int> IDPartner { get; set; }
        public string Partner { get; set; }
        public Nullable<int> IDDepartment { get; set; }
        public Nullable<int> IDClerk { get; set; }
        public Nullable<int> IDBrand { get; set; }
        public Nullable<decimal> ArrivalBaseQuantity { get; set; }
        public Nullable<decimal> ArrivalPrice { get; set; }
        public Nullable<decimal> ArrivalAmount { get; set; }
        public Nullable<decimal> DispatchBaseQuantity { get; set; }
        public Nullable<decimal> DispatchPrice { get; set; }
        public Nullable<decimal> DispatchAmount { get; set; }
        public Nullable<decimal> BaseQuantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> IDPartnerClass { get; set; }
        public Nullable<System.DateTime> AccountDate { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
