//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_0_EAP_Rpt_PU_PurchaseArrivalDetailRpt_d555d3e2_0e3d_ce75_b67d_2c3ce9f10199706
    {
        public Nullable<int> rowIndex { get; set; }
        public Nullable<System.DateTime> voucherdate { get; set; }
        public string PurchaseArrivalDTOCode { get; set; }
        public int voucherID { get; set; }
        public string VoucherType { get; set; }
        public string busiTypeName { get; set; }
        public string invoiceTypeName { get; set; }
        public Nullable<int> partnerClassID { get; set; }
        public string partnerName { get; set; }
        public int partnerID { get; set; }
        public Nullable<int> districtID { get; set; }
        public Nullable<int> departmentID { get; set; }
        public string departmentName { get; set; }
        public string personName { get; set; }
        public Nullable<int> IDProjectClass { get; set; }
        public Nullable<int> IDProject { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string currencyName { get; set; }
        public string PayType { get; set; }
        public string deliveryModeName { get; set; }
        public string AcceptAddress { get; set; }
        public Nullable<byte> IsReduceArrival { get; set; }
        public Nullable<decimal> origPaymentCashAmount { get; set; }
        public string voucherState { get; set; }
        public string inStockName { get; set; }
        public string SettleState { get; set; }
        public Nullable<int> inventoryClassID { get; set; }
        public string inventoryCode { get; set; }
        public string inventoryName { get; set; }
        public string specification { get; set; }
        public Nullable<int> IDBrand { get; set; }
        public string warehouseName { get; set; }
        public string unit1Name { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> origPrice { get; set; }
        public Nullable<decimal> discountRate { get; set; }
        public Nullable<decimal> origDiscountPrice { get; set; }
        public Nullable<decimal> taxRate { get; set; }
        public Nullable<decimal> origTaxPrice { get; set; }
        public Nullable<decimal> origDiscountAmount { get; set; }
        public Nullable<decimal> origTax { get; set; }
        public Nullable<decimal> origTaxAmount { get; set; }
        public Nullable<decimal> origDiscount { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public Nullable<byte> isPresent { get; set; }
        public Nullable<decimal> totalInQuantity { get; set; }
        public Nullable<decimal> totalinvoiceQuantity { get; set; }
        public Nullable<decimal> totalreturnQuantity { get; set; }
        public Nullable<decimal> totalReduceQuantity { get; set; }
        public Nullable<decimal> SDDetailorigSettleAmount { get; set; }
        public string saleOrderCode { get; set; }
        public Nullable<int> SaleOrderID { get; set; }
    }
}
