//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_0_GL_AccountAssociationForMu60
    {
        public int id2017 { get; set; }
        public string code2017 { get; set; }
        public string name2017 { get; set; }
        public Nullable<int> dcdirection2017 { get; set; }
        public Nullable<byte> isauxacccustomer { get; set; }
        public Nullable<byte> isauxaccdepartment { get; set; }
        public Nullable<byte> isauxaccperson { get; set; }
        public Nullable<byte> isauxaccproject { get; set; }
        public Nullable<byte> isauxaccinventory { get; set; }
        public Nullable<byte> isexauxacc1 { get; set; }
        public Nullable<byte> isexauxacc2 { get; set; }
        public Nullable<byte> isexauxacc3 { get; set; }
        public Nullable<byte> isexauxacc4 { get; set; }
        public Nullable<byte> isexauxacc5 { get; set; }
        public Nullable<byte> isexauxacc6 { get; set; }
        public Nullable<byte> isexauxacc7 { get; set; }
        public Nullable<byte> isexauxacc8 { get; set; }
        public Nullable<byte> isexauxacc9 { get; set; }
        public Nullable<byte> isexauxacc10 { get; set; }
    }
}
