//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_0_GL_TempDocSrcDocInfo_UserID_22
    {
        public string code { get; set; }
        public byte[] ts { get; set; }
        public string srcVoucherTimeStamp { get; set; }
        public string srcVoucherNo { get; set; }
        public int id { get; set; }
        public Nullable<int> idSrcBusiType { get; set; }
        public Nullable<int> srcvoucherid { get; set; }
        public Nullable<int> carryforwardtype { get; set; }
        public Nullable<int> idSrcVoucherType { get; set; }
        public Nullable<int> idTempDocDTO { get; set; }
        public Nullable<int> idTransactionDocDTO { get; set; }
        public Nullable<System.DateTime> srcVoucherDate { get; set; }
        public Nullable<int> idcurrency { get; set; }
        public Nullable<decimal> vOrigAmount { get; set; }
        public Nullable<decimal> vAmount { get; set; }
        public Nullable<int> idoutrdstyle { get; set; }
        public Nullable<int> idinrdstyle { get; set; }
        public Nullable<int> iddepartment { get; set; }
        public Nullable<int> idclerck { get; set; }
        public Nullable<int> idcustomer { get; set; }
        public string Memo { get; set; }
        public Nullable<int> idsupplier { get; set; }
        public string InvoiceCode { get; set; }
    }
}
