//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_0_GL_AuxBalanceSumRpt23
    {
        public int eap_reportrowtype { get; set; }
        public Nullable<int> accountTypeID { get; set; }
        public string accountTypeCode { get; set; }
        public string accountTypeName { get; set; }
        public Nullable<int> accountID { get; set; }
        public string accountCode { get; set; }
        public string accountName { get; set; }
        public Nullable<int> accountDcdirection { get; set; }
        public string AuxAccPersonName { get; set; }
        public Nullable<int> AuxAccPersonID { get; set; }
        public string AuxAccPersonCode { get; set; }
        public Nullable<int> currencyID { get; set; }
        public string currencyCode { get; set; }
        public string currencyName { get; set; }
        public Nullable<int> calDirection { get; set; }
        public Nullable<decimal> quantityBalance { get; set; }
        public Nullable<decimal> origAmountBalance { get; set; }
        public Nullable<decimal> amountBalance { get; set; }
        public Nullable<decimal> periodBeginBalanceQuantityDr { get; set; }
        public Nullable<decimal> periodBeginBalanceOrigAmountDr { get; set; }
        public Nullable<decimal> periodBeginBalanceAmountDr { get; set; }
        public Nullable<decimal> periodBeginBalanceQuantityCr { get; set; }
        public Nullable<decimal> periodBeginBalanceOrigAmountCr { get; set; }
        public Nullable<decimal> periodBeginBalanceAmountCr { get; set; }
        public Nullable<decimal> quantityDr { get; set; }
        public Nullable<decimal> origAmountDr { get; set; }
        public Nullable<decimal> amountDr { get; set; }
        public Nullable<decimal> quantityCr { get; set; }
        public Nullable<decimal> origAmountCr { get; set; }
        public Nullable<decimal> amountCr { get; set; }
        public Nullable<decimal> cumQuantityDr { get; set; }
        public Nullable<decimal> cumOrigAmountDr { get; set; }
        public Nullable<decimal> cumAmountDr { get; set; }
        public Nullable<decimal> cumQuantityCr { get; set; }
        public Nullable<decimal> cumOrigAmountCr { get; set; }
        public Nullable<decimal> cumAmountCr { get; set; }
        public Nullable<decimal> periodEndBalanceQuantityDr { get; set; }
        public Nullable<decimal> periodEndBalanceOrigAmountDr { get; set; }
        public Nullable<decimal> periodEndBalanceAmountDr { get; set; }
        public Nullable<decimal> periodEndBalanceQuantityCr { get; set; }
        public Nullable<decimal> periodEndBalanceOrigAmountCr { get; set; }
        public Nullable<decimal> periodEndBalanceAmountCr { get; set; }
    }
}
