//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_0_EAP_Rpt_ARAP_ReceiveVoucherDetailRpt_2f4622f4_075e_234c_e6f6_bd8e7afa28ce751
    {
        public Nullable<int> rowIndex { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string VoucherCode { get; set; }
        public int Idvoucher { get; set; }
        public Nullable<int> IdpartnerClass { get; set; }
        public Nullable<int> Idpartner { get; set; }
        public string partnerName { get; set; }
        public Nullable<int> Iddepartment { get; set; }
        public string departmentName { get; set; }
        public Nullable<int> IdsaleDepartment { get; set; }
        public Nullable<int> Idperson { get; set; }
        public string personName { get; set; }
        public Nullable<int> IdsaleMan { get; set; }
        public Nullable<int> Iddistrict { get; set; }
        public Nullable<int> IdbusiType { get; set; }
        public Nullable<int> Idcurrency { get; set; }
        public string currencyName { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<int> IdsettleTime { get; set; }
        public string settleTimeName { get; set; }
        public Nullable<int> IdsourceVoucherType { get; set; }
        public Nullable<int> IdsourceVoucher { get; set; }
        public Nullable<int> ProjectClassID { get; set; }
        public string ProjectClassName { get; set; }
        public Nullable<int> IdProject { get; set; }
        public Nullable<int> IdcancelState { get; set; }
        public string cancelStateName { get; set; }
        public Nullable<decimal> origAllowances { get; set; }
        public Nullable<int> IdsettleStyle { get; set; }
        public string settleStyleName { get; set; }
        public Nullable<int> IdbankAccount { get; set; }
        public string bankAccountCode { get; set; }
        public string bankAccountName { get; set; }
        public string documentCode { get; set; }
        public Nullable<decimal> origSettleDetailAmount { get; set; }
        public string maker { get; set; }
        public string memo { get; set; }
        public Nullable<int> Iddetail { get; set; }
    }
}
