//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_0_EAP_Rpt_SA_SaleOrderDetailRpt_505afee7_282a_2f75_ed84_104394c21ed4742
    {
        public Nullable<int> rowIndex { get; set; }
        public int voucherID { get; set; }
        public Nullable<System.DateTime> voucherdate { get; set; }
        public string SaleOrderCode { get; set; }
        public Nullable<int> partnerClassID { get; set; }
        public string partnerCode { get; set; }
        public string partnerName { get; set; }
        public Nullable<int> districtID { get; set; }
        public Nullable<int> departmentID { get; set; }
        public string personCode { get; set; }
        public Nullable<int> projectClassID { get; set; }
        public Nullable<int> IDProject { get; set; }
        public Nullable<int> IDSettleCustomerClass { get; set; }
        public Nullable<int> IDSettleCustomer { get; set; }
        public Nullable<int> IdBOM { get; set; }
        public Nullable<int> inventoryClassID { get; set; }
        public Nullable<int> warehouseID { get; set; }
        public int IDInventory { get; set; }
        public string inventoryName { get; set; }
        public string inventoryCode { get; set; }
        public string specification { get; set; }
        public Nullable<int> IDBrand { get; set; }
        public string unit1Name { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public string DetailMemo { get; set; }
        public Nullable<int> DataSourceID { get; set; }
        public int detailID { get; set; }
        public string DetailCode { get; set; }
        public string FirstDetailCode { get; set; }
    }
}
