//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_0_EAP_Rpt_ARAP_ReceiveAccountSumRpt_5a987305_41ab_c698_1e14_8239f6e52544865_Grp
    {
        public int grpid { get; set; }
        public Nullable<int> maxId { get; set; }
        public Nullable<int> minId { get; set; }
        public Nullable<int> Idpartner { get; set; }
        public int levelGrp { get; set; }
    }
}
