//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_1_SM_FC_TransactionEntry
    {
        public string code { get; set; }
        public string summary { get; set; }
        public Nullable<decimal> exchangerate { get; set; }
        public Nullable<decimal> origamountdr { get; set; }
        public Nullable<decimal> origamountcr { get; set; }
        public Nullable<decimal> amountdr { get; set; }
        public Nullable<decimal> amountcr { get; set; }
        public Nullable<decimal> quantitydr { get; set; }
        public Nullable<decimal> quantitycr { get; set; }
        public Nullable<decimal> price { get; set; }
        public string mergecode { get; set; }
        public Nullable<decimal> origamount { get; set; }
        public string billno { get; set; }
        public string memoto { get; set; }
        public string accounttype { get; set; }
        public string extend1 { get; set; }
        public Nullable<int> sequencenumber { get; set; }
        public byte[] ts { get; set; }
        public int id { get; set; }
        public Nullable<int> idaccount { get; set; }
        public Nullable<int> idcurrency { get; set; }
        public Nullable<int> dcdirection { get; set; }
        public Nullable<int> idauxiliaryinfo { get; set; }
        public Nullable<int> idTransactionDocDTO { get; set; }
        public Nullable<System.DateTime> billdate { get; set; }
        public Nullable<System.DateTime> generatedate { get; set; }
        public string GId { get; set; }
    }
}
