//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_eap_columnSet_User_BD8C4CE0A3184873A581578023BA866E
    {
        public string solutionName { get; set; }
        public string UserId { get; set; }
        public string Field { get; set; }
        public string QryField { get; set; }
        public Nullable<int> ColPos { get; set; }
        public string Caption { get; set; }
        public Nullable<bool> Fixed { get; set; }
        public int display { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<byte> Align { get; set; }
        public string OrderMode { get; set; }
        public Nullable<bool> MustSelect { get; set; }
        public Nullable<bool> NeedSum { get; set; }
        public bool IsSystem { get; set; }
        public Nullable<short> DecimalDigits { get; set; }
        public bool NeedReSetBooleanTxt { get; set; }
        public string BooleanTxt { get; set; }
        public Nullable<int> Precision { get; set; }
        public string FieldExpression { get; set; }
        public string DTOProp { get; set; }
        public string RefDtoProp { get; set; }
        public bool PropTitleCanChange { get; set; }
        public Nullable<bool> IsMergeColumn { get; set; }
        public Nullable<bool> DisplayOld { get; set; }
        public string ExpressionName { get; set; }
        public Nullable<bool> IsShowTotal { get; set; }
        public Nullable<bool> IsTotal { get; set; }
        public Nullable<int> idparent { get; set; }
        public Nullable<int> SolutionID { get; set; }
        public int id { get; set; }
    }
}
