//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_0_SM_FC_TransactionAuxiliaryInfo_UserID_23
    {
        public string code { get; set; }
        public string vouchercode { get; set; }
        public string invoicecode { get; set; }
        public Nullable<decimal> origamount { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public byte[] ts { get; set; }
        public int id { get; set; }
        public Nullable<int> idbankaccount { get; set; }
        public Nullable<int> idbusitype { get; set; }
        public Nullable<int> idcurrency { get; set; }
        public Nullable<int> iddepartment { get; set; }
        public Nullable<int> iddistrict { get; set; }
        public Nullable<int> iddocumentsusage { get; set; }
        public Nullable<int> idexpenseitem { get; set; }
        public Nullable<int> idincome { get; set; }
        public Nullable<int> idinventory { get; set; }
        public Nullable<int> idinventoryclass { get; set; }
        public Nullable<int> idinvlocation { get; set; }
        public Nullable<int> idcustomer { get; set; }
        public Nullable<int> idsupplier { get; set; }
        public Nullable<int> idcustomerclass { get; set; }
        public Nullable<int> idsupplierclass { get; set; }
        public Nullable<int> idperson { get; set; }
        public Nullable<int> idproject { get; set; }
        public Nullable<int> idprojectClass { get; set; }
        public Nullable<int> idinrdstyle { get; set; }
        public Nullable<int> idoutrdstyle { get; set; }
        public Nullable<int> idsettlestyle { get; set; }
        public Nullable<int> idUnit { get; set; }
        public Nullable<int> idwarehouse { get; set; }
        public Nullable<int> dcdirection { get; set; }
        public Nullable<int> idexauxacc1 { get; set; }
        public Nullable<int> idexauxacc10 { get; set; }
        public Nullable<int> idexauxacc2 { get; set; }
        public Nullable<int> idexauxacc3 { get; set; }
        public Nullable<int> idexauxacc4 { get; set; }
        public Nullable<int> idexauxacc5 { get; set; }
        public Nullable<int> idexauxacc6 { get; set; }
        public Nullable<int> idexauxacc7 { get; set; }
        public Nullable<int> idexauxacc8 { get; set; }
        public Nullable<int> idexauxacc9 { get; set; }
        public Nullable<int> idvouchertype { get; set; }
        public Nullable<int> idTransactionEntryDTO { get; set; }
        public Nullable<System.DateTime> voucherdate { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<int> idclerk { get; set; }
    }
}
