//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUFO_ReportTemplateFormulas
    {
        public string FormulaText { get; set; }
        public int Sheet { get; set; }
        public string SheetName { get; set; }
        public int ID { get; set; }
        public Nullable<int> UpdateFlag { get; set; }
        public int TemplateID { get; set; }
        public int UpdateID { get; set; }
    }
}
