//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUFO_ReportReject
    {
        public int Factor { get; set; }
        public string Symbol { get; set; }
        public int Digits { get; set; }
        public string FormulaArea { get; set; }
        public string Expression { get; set; }
        public int ID { get; set; }
        public Nullable<int> ReportID { get; set; }
    }
}
