//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUFO_ReportType
    {
        public string Name { get; set; }
        public string Code { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int IsSystem { get; set; }
        public int TypeLevel { get; set; }
        public string SubSysId { get; set; }
        public Nullable<int> HasChild { get; set; }
        public int ID { get; set; }
        public int TypeState { get; set; }
        public int IsEndNode { get; set; }
        public string InId { get; set; }
        public Nullable<int> NumbID { get; set; }
        public Nullable<int> IdParent { get; set; }
    }
}
