//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUFO_ReportFormula
    {
        public string FormulaCode { get; set; }
        public string FormulaName { get; set; }
        public string FormulaTitle { get; set; }
        public string FormulaFormat { get; set; }
        public string FormulaDescription { get; set; }
        public string FormulaHelp { get; set; }
        public bool IsHasReference { get; set; }
        public string ReferenceUrl { get; set; }
        public int ShowIndex { get; set; }
        public string Example { get; set; }
        public int ID { get; set; }
        public string LinkUrl { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public int TypeID { get; set; }
    }
}
