//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUFO_ReportTemplateBasic
    {
        public string TemplateName { get; set; }
        public string Code { get; set; }
        public string SubSysId { get; set; }
        public string Memo { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Updater { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<int> TemplateFlag { get; set; }
        public Nullable<int> InSubSys { get; set; }
        public byte[] TS { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public string MenuCode { get; set; }
        public string ParentMenuCode { get; set; }
        public int ID { get; set; }
        public int TemplateID { get; set; }
        public Nullable<int> CopyFrom { get; set; }
        public int TypeID { get; set; }
        public int UpdateID { get; set; }
    }
}
