//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUFO_ReportFormulaType
    {
        public string TypeName { get; set; }
        public string SubSysId { get; set; }
        public string Assembly { get; set; }
        public string ClassName { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<int> Flag { get; set; }
        public int ID { get; set; }
        public Nullable<int> Position { get; set; }
        public int TypeLevel { get; set; }
        public Nullable<int> IsEndNode { get; set; }
        public Nullable<int> IdParent { get; set; }
    }
}
