//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.TModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUFO_SYSReportTemplateModel
    {
        public string TemplateStyle { get; set; }
        public byte[] TS { get; set; }
        public int Sheet { get; set; }
        public int Rows { get; set; }
        public int Cols { get; set; }
        public string SheetName { get; set; }
        public string SubSysId { get; set; }
        public int TemplateID { get; set; }
        public int UpdateID { get; set; }
    }
}
