//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarNumber
    {
        public CarNumber()
        {
            this.GongLuBaoXiaoBills = new HashSet<GongLuBaoXiaoBill>();
        }
    
        public int ID { get; set; }
        public string CarNumber1 { get; set; }
        public short Del { get; set; }
    
        public virtual ICollection<GongLuBaoXiaoBill> GongLuBaoXiaoBills { get; set; }
    }
}
