//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareFileOrNotice
    {
        public int ID { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> FileTypeID { get; set; }
        public string BeiZhu { get; set; }
        public string FileURL { get; set; }
        public Nullable<System.DateTime> UploadFileTime { get; set; }
        public int ShareUser { get; set; }
        public string ShareToUser { get; set; }
        public string ModelList { get; set; }
    
        public virtual FileType FileType { get; set; }
        public virtual ShareType ShareType { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
