//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BaoXiaoBill
    {
        public T_BaoXiaoBill()
        {
            this.T_BaoxiaoItems = new HashSet<T_BaoxiaoItems>();
        }
    
        public long ID { get; set; }
        public string BaoxianDanwei { get; set; }
        public Nullable<System.DateTime> IntTime { get; set; }
        public short Del { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public Nullable<int> AddUserID { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<T_BaoxiaoItems> T_BaoxiaoItems { get; set; }
    }
}
