//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BaoJiaToP
    {
        public T_BaoJiaToP()
        {
            this.T_WinBak = new HashSet<T_WinBak>();
            this.YXB_Baojia = new HashSet<YXB_Baojia>();
        }
    
        public long id { get; set; }
        public int Kh_List_id { get; set; }
        public Nullable<System.DateTime> GhTime { get; set; }
        public string JiShuYaoQiu { get; set; }
        public string Addess { get; set; }
        public string DaiBanYunShu { get; set; }
        public string JieShuanFanShi { get; set; }
        public string HeTongQianDing { get; set; }
        public System.DateTime AddTime { get; set; }
        public short DelFlag { get; set; }
        public string KHComname { get; set; }
        public Nullable<int> HanShuiID { get; set; }
    
        public virtual T_BoolItem T_BoolItem { get; set; }
        public virtual YXB_Kh_list YXB_Kh_list { get; set; }
        public virtual ICollection<T_WinBak> T_WinBak { get; set; }
        public virtual ICollection<YXB_Baojia> YXB_Baojia { get; set; }
    }
}
