//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SCCJ
    {
        public long ID { get; set; }
        public System.DateTime Wtime { get; set; }
        public int BuMenid { get; set; }
        public long ProductNameId { get; set; }
        public long ProductGGId { get; set; }
        public long ProductJB { get; set; }
        public short Del_f { get; set; }
        public Nullable<int> JiaYouDengPinNum { get; set; }
        public int JiaYiDengPinNum { get; set; }
        public int JiaHeGePinNum { get; set; }
        public int JiaCiPinNum { get; set; }
        public Nullable<int> JiaFeiPinNum { get; set; }
        public Nullable<int> YiYouDengPinNum { get; set; }
        public int YiYiDengPinNum { get; set; }
        public int YiHeGePinNum { get; set; }
        public int YiCiPinNum { get; set; }
        public Nullable<int> YiFeiPinNum { get; set; }
    
        public virtual BumenInfoSet BumenInfoSet { get; set; }
        public virtual T_ChanPinName T_ChanPinName { get; set; }
        public virtual T_ChanPinName T_ChanPinName1 { get; set; }
        public virtual T_ChanPinName T_ChanPinName2 { get; set; }
    }
}
