//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WinBakFaHuo
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> FaHuoTime { get; set; }
        public Nullable<int> AddUser { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string FaHuoBak { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public Nullable<decimal> EditQianFahuoInt { get; set; }
        public Nullable<int> EditUser { get; set; }
        public Nullable<short> Del { get; set; }
        public long BaoJia_ID { get; set; }
        public Nullable<decimal> FahuoInt { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
        public virtual YXB_Baojia YXB_Baojia { get; set; }
    }
}
