//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YXB_Baojia
    {
        public YXB_Baojia()
        {
            this.T_WinBakFaHuo = new HashSet<T_WinBakFaHuo>();
            this.YXB_BaoJiaEidtMoney = new HashSet<YXB_BaoJiaEidtMoney>();
        }
    
        public long id { get; set; }
        public long BaoJiaTop_id { get; set; }
        public string CPname { get; set; }
        public string CPXingHao { get; set; }
        public string CPGuiGe { get; set; }
        public decimal CPShuLiang { get; set; }
        public System.DateTime AddTime { get; set; }
        public int ZhuangTai { get; set; }
        public Nullable<decimal> BaoJiaMoney { get; set; }
        public Nullable<int> BaoJiaPerson { get; set; }
        public Nullable<System.DateTime> BaoJiaTime { get; set; }
        public Nullable<double> WIN { get; set; }
        public short DelFlag { get; set; }
        public Nullable<decimal> EditQianMoney { get; set; }
        public Nullable<System.DateTime> UpdataTime { get; set; }
        public Nullable<int> UpdataUserID { get; set; }
        public Nullable<decimal> WinMoney { get; set; }
        public Nullable<decimal> BaoJiaYunFei { get; set; }
        public Nullable<decimal> EditQianYunFei { get; set; }
        public Nullable<decimal> WinYunFei { get; set; }
        public string Remark { get; set; }
        public Nullable<long> CPDengJiID { get; set; }
        public Nullable<short> CheckMoney { get; set; }
        public Nullable<System.DateTime> GhOverTime { get; set; }
    
        public virtual T_BaoJiaToP T_BaoJiaToP { get; set; }
        public virtual T_ChanPinName T_ChanPinName { get; set; }
        public virtual ICollection<T_WinBakFaHuo> T_WinBakFaHuo { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<YXB_BaoJiaEidtMoney> YXB_BaoJiaEidtMoney { get; set; }
    }
}
