//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YXB_Kh_list
    {
        public YXB_Kh_list()
        {
            this.T_BaoJiaToP = new HashSet<T_BaoJiaToP>();
        }
    
        public int id { get; set; }
        public string KHname { get; set; }
        public string KHComname { get; set; }
        public string KHperson { get; set; }
        public string KHzhiwu { get; set; }
        public string KHphoto { get; set; }
        public string KHfaren { get; set; }
        public short DelFlag { get; set; }
        public string Remark { get; set; }
        public System.DateTime NewTime { get; set; }
        public int AddUser { get; set; }
        public short All_I { get; set; }
        public string KHSGAdrss { get; set; }
        public string BeiZhu { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<T_BaoJiaToP> T_BaoJiaToP { get; set; }
    }
}
