//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YXB_BaoJiaEidtMoney
    {
        public long ID { get; set; }
        public long YXB_BJ_ID { get; set; }
        public int EidtUser_ID { get; set; }
        public System.DateTime EidtTime { get; set; }
        public decimal EditBJMoney { get; set; }
        public Nullable<decimal> EditYFMoney { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual YXB_Baojia YXB_Baojia { get; set; }
    }
}
